### ISSUE TITLE
Slider position dot twice rendered

### ISSUE THREAD

**Issue by rojnwa** [nimsandu/spicetify-bloom#10]
Hey, first things first: your theme looks great! Thanks for creating it.
Ugly part now: for every slider (song position, volume) the dot, marking the position, is being rendered twice. once at the correct position and once directly beneath it.

spicetify version: 2.9.8
spotify version: 1.1.85.895.g2a71e1b8 (windows)

![image](https://user-images.githubusercontent.com/19150352/168895374-38527ed1-cba3-435d-a63e-2b2651866165.png)

**Comment by nimsandu** [comment]
you have to completely uninstall
>spicetify
>theme
>spotify 
and try installing again
that must fix it
