### ISSUE TITLE
Liked songs and Episodes not showing + Dubble dots on the progressbar and volumebar

### ISSUE THREAD

**Issue by Sefohui** [nimsandu/spicetify-bloom#100]
So as the title states I cannot see the "Likes Songs" and "Your Episodes" buttons on the sidebar. They are there just not visible (See picture)

And the sliders for the progressbar and the volumebar is shown two times beneath eachoter. (See picture)

I have done the automatic installation and also checked with the manual to be sure.

My config:
`[Setting]
prefs_path              = C:\Users\kevin\AppData\Roaming\Spotify\prefs
color_scheme            = dark
inject_css              = 1
overwrite_assets        = 1
check_spicetify_upgrade = 0
spotify_path            = C:\Users\kevin\AppData\Roaming\Spotify
current_theme           = Bloom
replace_colors          = 1
spotify_launch_flags    = 

[Preprocesses]
remove_rtl_rule       = 1
expose_apis           = 1
disable_upgrade_check = 1
disable_sentry        = 1
disable_ui_logging    = 1

[AdditionalOptions]
extensions            = bloom.js
custom_apps           = marketplace
sidebar_config        = 1
home_config           = 1
experimental_features = 1

; DO NOT CHANGE!
[Backup]
version = 1.1.88.612.gcc529952
with    = 2.10.2

[Patch]
xpui.js_find_8008 = ,(\w+=)32,
xpui.js_repl_8008 = ,${1}56,

` 
![image](https://user-images.githubusercontent.com/69700015/188217097-ce51951e-d1a2-4c09-a0b9-394b74401a50.png)
![image](https://user-images.githubusercontent.com/69700015/188217114-fe048af9-5b3e-4ba2-bfd6-a9eb332582ec.png)

**Comment by nimsandu** [comment]
@Sefohui  your spicetify version is 2.10.2 which is not the latest spicetify version (latest version is 2.12)
update spicetify by running `spicetify upgrade ` after backing up progress run bloom installation script again 
`Invoke-WebRequest -UseBasicParsing "https://raw.githubusercontent.com/nimsandu/spicetify-bloom/main/install.ps1" | Invoke-Expression`
it must fix the issue

**Comment by wadforth** [comment]
Can confirm on the double bubble issue. Latest version here.

![image](https://user-images.githubusercontent.com/45768489/188281707-8cfe7c08-4c69-4086-87c3-8067fd8f2a64.png)

**Comment by Sefohui** [comment]
It started working for me after the update aswell. Now. When I loaded back the theme in marketplace to change the color easy the dubble bubble re-appeared. Fixed this by removing it from the marketplace again and changing the color in terminal

**Comment by wadforth** [comment]
> 

Ah, that did it :P Double bubble fixed!

**Comment by Sefohui** [comment]
Yeah took me a while to figure that out aswell. Guess it doesn't really like being applied two times lol. Then I guess we can close this now :D

**Comment by nimsandu** [comment]
@wadforth @Sefohui Thanks for your troubleshooting and finding a proper solution I really appreciate that

If someone get this issue again ill reference this issue so this issue will help lots of bloom family members 

If you are having any issues in future don't hesitate to open another issue 

Enjoy bloom 
Thanks
