### ISSUE TITLE
Play button on playlists not working/appearing

### ISSUE THREAD

**Issue by Georgetheasian** [nimsandu/spicetify-bloom#101]
The play button either does not appear or does not work. This issue only appears to be on daily mixes and playlist tiles.

**Comment by Georgetheasian** [comment]
![image](https://user-images.githubusercontent.com/80559769/188782236-9d5d8560-363a-463b-82c5-659b6f39c27b.png)

![image](https://user-images.githubusercontent.com/80559769/188782312-249c1a61-18e8-461e-89be-e8b9796e42a0.png)

**Comment by nimsandu** [comment]
I have problem while fixing this issue 
can someone help? 🙃
I would really appreciate it
![image](https://user-images.githubusercontent.com/57834844/189830494-ca755e74-75e2-452c-bca8-303d626192cc.png)
it became something like this👆🏻

**Comment by DoctorAnon** [comment]
Same issue, literally any button would be good 
![4](https://user-images.githubusercontent.com/71120469/190230092-9a4f9a16-27a6-4b78-a95b-c47b4555cf3f.png)

**Comment by nimsandu** [comment]
@DoctorAnon If you search an artist inside artist page there is the play button just like it suppose to be and then if you go anywhere where once didn't have the play button will now have the perfect play button 

I don't know why🥲

**Comment by RACECAR69** [comment]
in my case it appears but does not work
the animation of being clicked plays but it does nothing
![image](https://user-images.githubusercontent.com/71834151/190841246-f49f24b4-94c3-4314-accb-b721623db23f.png)

**Comment by nimsandu** [comment]
Im going to leave #110 pr unmerged for someone to contribute to fix this

**Comment by leonglo** [comment]
hey @nimsandu 
do you  have any ideas on how to fix the play button not working?

**Comment by windowz414** [comment]
@leonglo-

Can you send a screenshot from your user interface? Can it be because the interface is borked?

**Comment by leonglo** [comment]
@windowz414 

https://user-images.githubusercontent.com/75845683/196757589-4764d0ef-c978-48d3-bc95-63a0e37c88e7.mp4

**Comment by windowz414** [comment]
@leonglo -

Now this one is weird. I'll see if I can reproduce this on my laptop with Windows 10.

**Comment by nimsandu** [comment]
@leonglo I have no idea cuz sometimes it works but sometimes it's not 

Im trying yo figure out why but  nothing worked

**Comment by nimsandu** [comment]
@windowz414 Thanks mate

**Comment by leonglo** [comment]
Hopefully we find the reason

**Comment by windowz414** [comment]
@nimsandu you're always welcome!

**Comment by windowz414** [comment]
@leonglo, I cannot reproduce your issue because there's a worse bug on my side about this.

@nimsandu, the play button doesn't appear on my side at all. Alongside, there seems to be some kind of an internal windows container (Even I have no idea how else to describe this.) borders as well.

![image](https://user-images.githubusercontent.com/39265461/196906751-04632aa4-01d8-41d9-a01a-37d5a2fc3250.png)

**Comment by leonglo** [comment]
Damn!

**Comment by windowz414** [comment]
@nimsandu sorry for duplicate ping but I think you're going to want to see this.

I've decided to go through some element inspection using Chrome to see if I can find anything useful. And I *did* find something useful that *might* help you through;

The play button *does* exist but for some odd reason, the vector image doesn't show up. (Missing property? Partial info? The play/pause button of action bar row has less vector paths defined compared to remove from library button.)

![image](https://user-images.githubusercontent.com/39265461/196910545-77d112c4-4868-4eaa-af02-3a8971020f38.png)

**Comment by nimsandu** [comment]
@windowz414 Yhah thats what i cant understand too

BTW Update Spotify so you will have old ui for Spotify

**Comment by windowz414** [comment]
@nimsandu well, I guess it's time for a rewrite?

Also sure, I'll do so when this Windows update is done. xd

**Comment by nimsandu** [comment]
> @nimsandu well, I guess it's time for a rewrite?
> 

I guess so

> Also sure, I'll do so when this Windows update is done. xd

Nice

**Comment by nimsandu** [comment]
with the introduction of spicetify version 2.14.3 play button appeared again
now we have to work regarding making the button accessible again

**Comment by windowz414** [comment]
@nimsandu I'll see if we can leverage from other themes regarding this.

I can confirm the button appears but has no functionality BTW.

**Comment by otutsukihyuuga** [comment]
not just the play button on collection of songs(albums and playlist) and top search result but also shuffle doesnt work (the button on left of previous button) along with the loop (button on right of next button) on hovering it lightens if not already selected but onclick nothing happens

**Comment by miukyo** [comment]
i managed to fix the play button issue where the button doesn't do anything when you click it.

Your selector in bloom.js are wrong because you selecting the div element not the button so i change the selector to the button and it works fine

`.main-playButton-PlayButton` to `.main-playButton-PlayButton>button`

```js
playButtonStyle.innerHTML = `
      .main-playButton-button[aria-label="${Spicetify.Platform.Translations.play}"],
      .main-playButton-PlayButton>button[aria-label="${Spicetify.Platform.Translations.play}"],
      .main-playPauseButton-button[aria-label="${Spicetify.Platform.Translations.play}"],
      .main-trackList-rowPlayPauseButton[aria-label="${Spicetify.Platform.Translations.play}"] {
        background-color: var(--spice-text) !important;
        -webkit-mask-image: url('https://cdn.jsdelivr.net/gh/nimsandu/spicetify-bloom@master/assets/fluentui-system-icons/ic_fluent_play_24_filled.svg') !important;
      }
      .main-playButton-button[aria-label="${Spicetify.Platform.Translations.pause}"],
      .main-playButton-PlayButton>button[aria-label="${Spicetify.Platform.Translations.pause}"],
      .main-playPauseButton-button[aria-label="${Spicetify.Platform.Translations.pause}"],
      .main-trackList-rowPlayPauseButton[aria-label="${Spicetify.Platform.Translations.pause}"] {
        background-color: var(--spice-text) !important;
        -webkit-mask-image: url('https://cdn.jsdelivr.net/gh/nimsandu/spicetify-bloom@master/assets/fluentui-system-icons/ic_fluent_pause_16_filled.svg') !important;
      }`;
 ```
 
 your `playButtonStyle.type = 'text/css';` are unnecessary so i remove it
 
 i also change some css to fix the original button overlapping the modded one and changing `.main-playButton-PlayButton` to `.main-playButton-PlayButton>button`
 
 ```css
 /* play buttons */
 
 .main-playButton-button,
.main-playButton-PlayButton > button,
.main-trackList-rowPlayPauseButton {
  background-color: var(--spice-text) !important;
  -webkit-mask-image: url("https://cdn.jsdelivr.net/gh/nimsandu/spicetify-bloom@master/assets/fluentui-system-icons/ic_fluent_play_24_filled.svg");
}

.main-playButton-PlayButton:focus,
.main-playButton-PlayButton:hover {
  background-color: transparent;
}

.main-playButton-PlayButton > button {
  width: var(--size);
  height: var(--size);
}

.main-playButton-PlayButton > button > span {
  display: none;
}
```

sorry for my bad english i tried my best :D

**Comment by windowz414** [comment]
> @windowz414 could u tell me how u used inspect element in spotify app??

While having a running instance of Spotify, I did this from CLI;
```
spicetify enable-devtools
```

Then invoked DevTools with Ctrl+Alt+I or F12.

**Comment by windowz414** [comment]
@miukyo excellent work. Can you open a PR to this repo so it will be tested in a wider range in an easier way?

**Comment by miukyo** [comment]
@windowz414 sure, i just did it

**Comment by otutsukihyuuga** [comment]
@miukyo ur work is really great i edited my files and it worked 
Thanks a lot bro

**Comment by miukyo** [comment]
@otutsukihyuuga thank you

**Comment by nimsandu** [comment]
@windowz414 @miukyo @otutsukihyuuga great work guys!
i really appreciate this 
thank you all to making our themes' future way better day after day!
have a nice life!

**Comment by windowz414** [comment]
> @windowz414 @miukyo @otutsukihyuuga great work guys! i really appreciate this thank you all to making our themes' future way better day after day! have a nice life!

@nimsandu any time and thank you for making such a beautiful theme too! You too have a nice life! <3
