### ISSUE TITLE
Clicking on playlist jumps playlist slider to top, impossible to double-click to play

### ISSUE THREAD

**Issue by ghost** [nimsandu/spicetify-bloom#102]
Installation Method: Marketplace
Spotify Version: Spotify for Windows 1.1.93.896.g3ae3b4f3
Spicetify Version: Latest

   1. Scroll down to play playlist lower down on your playlist bar list
   2. Click playlist icon
   3. Try to click it again to play the playlist
   4. You cannot, because the scrollbar jumps up, so you cannot doubleclick to play
   5. Now you must scroll down and then press it again to play
   
   Issue does not seem to occur when installing via cli, only via Marketplace - however the cli version has its own issues like duplicate dots.
   
   **Screenshots Below with descriptions:** 
![1](https://user-images.githubusercontent.com/71120469/190229733-944269d9-553e-49ef-b826-66e5917b176b.png)
**^ Default on app open**
![2](https://user-images.githubusercontent.com/71120469/190229858-9adc0e54-2eae-4dcd-a11e-855ceeb3bea6.png)
**^ After Scrolling down**
![3](https://user-images.githubusercontent.com/71120469/190229909-1cf41d49-caf1-492c-ae4c-cfbcd0115d3f.png)
**^After pressing a playlist on the bottom**

**Comment by nimsandu** [comment]
@DoctorAnon It only happens if you install bloom via marketplace right?

**Comment by nimsandu** [comment]
fixed in latest versions 
if the issue still presents uninstall playlist icon extension from marketplace
