### ISSUE TITLE
[Spotify 1.1.94.870] Design is broken entirely

### ISSUE THREAD

**Issue by windowz414** [nimsandu/spicetify-bloom#103]
I have no idea why and how, but the design is entirely broken on the latest version of Spotify (the one specified in the title).

![image](https://user-images.githubusercontent.com/39265461/190724337-8bcd35a3-8397-4f2d-b2ab-590f4bac00af.png)

**Comment by nimsandu** [comment]
It usually happens with a new Spotify version all the time

Then after spicetify latest release everything become

What is your spicetfy version?

**Comment by windowz414** [comment]
> It usually happens with a new Spotify version all the time
> 
> Then after spicetify latest release everything become
> 
> What is your spicetfy version?

It in fact got installed when I was installing the theme through its script.

```
C:\Users\shins>spicetify --version
2.13.1
```

**Comment by nimsandu** [comment]
Can you run it again and see what happens

**Comment by windowz414** [comment]
> Can you run it again and see what happens 

Well in fact, I ran it for the 3rd time when taking that screenshot. Even restarted.

**Comment by nimsandu** [comment]
Oh sorry to hear that 
Can you completely remove all spicetify files and restore default Spotify ui and then run the script again
Sorry to bother you

**Comment by nimsandu** [comment]
```
Invoke-WebRequest -UseBasicParsing "https://raw.githubusercontent.com/nimsandu/spicetify-bloom/main/install.ps1" | Invoke-Expression
```

**Comment by windowz414** [comment]
> Oh sorry to hear that 
> Can you completely remove all spicetify files and restore default Spotify ui and then run the script again

Sure thing, I'll try when I'm back home, I'm currently outside.

> Sorry to bother you 

It's okay, I'm just the user here. Nothing to apologize for. :)

**Comment by nimsandu** [comment]
@windowz414 a User is a family member for us

**Comment by windowz414** [comment]
> @windowz414 a User is a family member for us

Aww ;w;

**Comment by windowz414** [comment]
> ```
> Invoke-WebRequest -UseBasicParsing "https://raw.githubusercontent.com/nimsandu/spicetify-bloom/main/install.ps1" | Invoke-Expression
> ```

Unfortunately that didn't quite work. Still the same thing even after a completely reinstallation of Spotify after removing Spicetify with all its data.

**Comment by nimsandu** [comment]
Ill look into this issue 
And if spicetfy-cli release a new version upgrade spicetfy asap
It fixes the issues 
But ill see what I can do 

@kyrie25 @MGPlayzYT any suggestions?

**Comment by windowz414** [comment]
> Ill look into this issue 
> And if spicetfy-cli release a new version upgrade spicetfy asap
> It fixes the issues 
> But ill see what I can do 

Thank you so much, good luck! :3

**Comment by nimsandu** [comment]
i dont know why but mine is completely fine even after running the script several times
![image](https://user-images.githubusercontent.com/57834844/191398260-5984630b-d12d-4d88-bcd0-f4cec6b6d32b.png)

**Comment by windowz414** [comment]
> i dont know why but mine is completely fine even after running the script several times
> ![image](https://user-images.githubusercontent.com/57834844/191398260-5984630b-d12d-4d88-bcd0-f4cec6b6d32b.png)
> 

Now that's weird, I'll retry later today and return back here.

**Comment by nimsandu** [comment]
https://github.com/nimsandu/spicetify-bloom/issues/95#issuecomment-1238868804
try these steps

**Comment by windowz414** [comment]
> https://github.com/nimsandu/spicetify-bloom/issues/95#issuecomment-1238868804
> try these steps 

Thanks for the ref!

**Comment by windowz414** [comment]
After a whole day of testing and messing around, I FINALLY found the cause of this.

That mess happens when a non-existent custom app and/or resource are/is loaded in Spicetify. I was trying to load to Marketplace but apparently they renamed it to just `marketplace` instead of `spicetify-marketplace`, which is what caused this issue.

I made sure the theme is installed the last just in case resources need to be overridden by theme as well.

I'll also need to update FMS Windows installation script to use new methods and such, it's so damn outdated.

Thanks for the help still! Appreciate it!

[+Cc: @pronoy2108]

**Comment by nimsandu** [comment]
❤️

**Comment by nimsandu** [comment]
@windowz414 can i close this issue?
but i would like you to add your solution to the readme troubleshoot section (when adding add this line on the end 
## credit [@windowz414](https://github.com/windowz414). for troubleshoot process   )

**Comment by windowz414** [comment]
> @windowz414 can i close this issue?
> but i would like you to add your solution to the readme troubleshoot section (when adding add this line on the end 
> ## credit [@windowz414](https://github.com/windowz414). for troubleshoot process   )

Yep, it's okay to close as it's resolved. I'll ensure to open a PR later today that explains the troubleshooting process in a less technical way.

**Comment by nimsandu** [comment]
@windowz414 thanks for everything you done
i really appreciate you
and i humbly invite you to stay with bloom and help all our users to experience a better theme
thanks

**Comment by windowz414** [comment]
> @windowz414 thanks for everything you done
> i really appreciate you
> and i humbly invite you to stay with bloom and help all our users to experience a better theme
> thanks

I shall thank you for all the kindness, support and time thinking you have given during troubleshooting this. I'm just a tinkerer. You're the actual G.O.A.T. ;3

**Comment by nimsandu** [comment]
@windowz414 thanks❤️

**Comment by windowz414** [comment]
> @windowz414 great job on the solution part! glad you could help out.
> sorry for the inactivity lately @nimsandu, been busy with irl stuff

Thank you! I just tinkered around to find it out. x3

Also it's okay about inactivity, life is more important than anything virtual. /srs
