### ISSUE TITLE
Add Icons for Reddit And New Release Apps

### ISSUE THREAD

**Issue by foco76** [nimsandu/spicetify-bloom#104]
Add icons for reddit and new release apps or allow to use default app icon instead of replacing all app icons with library icon!
Thank You!
(If you Can Put Normal Like Button And Playlist Images and reduce the player size to uncover sidebar[hard to select playlists player take all the space])

**Comment by nimsandu** [comment]
@foco76 Thanks for your suggestion 
We really appreciate it 
We will work regarding this after fixing current issues
