### ISSUE TITLE
Latest update: top bar and the home button go missing

### ISSUE THREAD

**Issue by DUCKONAROLL** [nimsandu/spicetify-bloom#105]
old title: Not all lyrics shown as bottom bar blocks it

**Comment by nimsandu** [comment]
can you add a screenshot

**Comment by DUCKONAROLL** [comment]
latest spotify update actually fixes it but the entire top bar and the home button go missing

**Comment by nimsandu** [comment]
can you add a screenshot regarding that issue sir

**Comment by Georgetheasian** [comment]
@nimsandu I have the same issue, just updated my spotify and it looks like this. 

![image](https://user-images.githubusercontent.com/80559769/192122241-e1d93d0a-2335-4740-85e0-35ea20b858c2.png)

**Comment by nimsandu** [comment]
have you tried running the installation script again?

**Comment by Oosl** [comment]
> have you tried running the installation script again?

I have the same issue too and I has tried to reinstall script again, but it was not work.
![image](https://user-images.githubusercontent.com/27420243/192430686-a6dfa1cb-3f36-4679-85b1-e1a39733db91.png)

**Comment by Georgetheasian** [comment]
Its because of the new default UI for Spotify. 
![image](https://user-images.githubusercontent.com/80559769/192437735-bf40ee7e-7541-435b-b974-5252be9fff56.png)

**Comment by nimsandu** [comment]
@Oosl try updating Spotify to Spotify for Windows
1.1.96.785.g464c973a it will fix the issue

**Comment by nimsandu** [comment]
let me know after updating spotify to the latest version

**Comment by Oosl** [comment]
> @Oosl try updating Spotify to Spotify for Windows 1.1.96.785.g464c973a it will fix the issue

yes, it has been fixed on Spotify for Windows 1.1.96.785.g464c973a.

**Comment by nimsandu** [comment]
@Oosl Glad to hear that
Enjoy bloom 

Please Don't hesitate to let us know if there is any other problem

Can we close this issue now?

**Comment by Oosl** [comment]
@nimsandu no any other problems now. I think this issue can be closed and thanks for your work.

**Comment by nimsandu** [comment]
thanks you both  @Oosl @DUCKONAROLL  and everyone who participated 

Enjoy bloom
