### ISSUE TITLE
Installation Script Doesn't Work With GNU + Linux

### ISSUE THREAD

**Issue by Briiqn** [nimsandu/spicetify-bloom#11]

**Comment by stpnwf** [comment]
I had to install it manually. The script has many issues, from referencing `fluent.js` rather than `bloom.js`
to trying to extract files to `~/spicetify-cli` rather than `~/.config/spicetify`

**Comment by nimsandu** [comment]
can you fix that and create a PR 
plz

**Comment by pronoy2108** [comment]
> 
Maybe try wget instead of curl/

**Comment by stpnwf** [comment]
> can you fix that and create a PR plz

Will give it a try.

> Maybe try wget instead of curl/
Yeah, I tried wget but I couldn't get it to rename the download file for some reason. I will try it again without renaming.
