### ISSUE TITLE
Multiple dots on progress bar

### ISSUE THREAD

**Issue by Flonky** [nimsandu/spicetify-bloom#111]
## Screenshots
![image](https://user-images.githubusercontent.com/64008721/192192129-9eda5e4a-886c-42b3-be9d-d7ad21ad306d.png)

## Description
In the song progress & volume bar, the dots at the end have a second dot below.

**Comment by nimsandu** [comment]
can you send a screenshot of your xpui file

**Comment by Flonky** [comment]
I assume you are referring to this one?
![image](https://user-images.githubusercontent.com/64008721/192198807-de2c57e3-9212-4900-badf-3131482e5f50.png)

**Comment by nimsandu** [comment]
@Flonky Yes 

You have installed the theme using marketplace 

Uninstall the theme from marketplace and run the installation script on the readme

That will fix the issue

**Comment by Flonky** [comment]
Thanks!
