### ISSUE TITLE
Black object on screen

### ISSUE THREAD

**Issue by mscodepl** [nimsandu/spicetify-bloom#112]
![Zrzut ekranu 2022-09-29 205056](https://user-images.githubusercontent.com/41286754/193117693-10fd6aaf-61fc-4851-9142-c4b96f5f7234.png)

How to remove this object?

**Comment by Sebasssssss** [comment]
I have the same problem

**Comment by rawpie2** [comment]
I also have this problem

**Comment by iDCoded** [comment]
Facing the exact same issue. Waiting for a fix...

**Comment by nimsandu** [comment]
try updating Spotify to Spotify for Windows
1.1.96.785.g464c973a it will fix the issue
by updating we will have the old spotify ui so the theme will work fine with the latest spotify version

**Comment by nimsandu** [comment]
let me know after updating spotify version

**Comment by mscodepl** [comment]
> let me know after updating spotify version 

Repaired :)

**Comment by nimsandu** [comment]
Closing issue as fixed 
@mscodepl and everyone 
Thanks for reaching out
Enjoy bloom
And don't hesitate to open another issue if you have any other problem
