### ISSUE TITLE
Can't click on playlist when is downloaded

### ISSUE THREAD

**Issue by 7evenlxrd** [nimsandu/spicetify-bloom#116]
It looks like the download icon on the playlist disturbs the cursor and cannot be clicked, it only works when clicking on the corner of the playlist. Playlists that are not downloaded can be clicked freely

![obraz](https://user-images.githubusercontent.com/49694911/196516615-adf8a3d2-bf2a-4ee3-9659-52d1cdee765a.png)
![obraz](https://user-images.githubusercontent.com/49694911/196516537-1a1004b2-5a62-4948-9c7d-c4168f3e9a5a.png)

**Comment by 7evenlxrd** [comment]
I can't make screenshot with cursor.

**Comment by nimsandu** [comment]
@7evenlxrd what if we move download icon to a corner?
will it work in your opinion

**Comment by 7evenlxrd** [comment]
It should work better than now sure

**Comment by SunsetTechuila** [comment]
@7evenlxrd hello, is it still relevant?

**Comment by SunsetTechuila** [comment]
closing as stale
