### ISSUE TITLE
dark theme doesn't apply

### ISSUE THREAD

**Issue by Kordex1337** [nimsandu/spicetify-bloom#117]
it doesn't apply, i did everything by instruction

**Comment by nimsandu** [comment]
are you using marketplace version @Kordex1337 ?

**Comment by nimsandu** [comment]
just run this script it will apply the dark scheme and it will fix anything which is wrong with theme

before proceeding remove bloom through marketplace if you are using marketplace version

 ### Windows (Powershell)

```powershell
Invoke-WebRequest -UseBasicParsing "https://raw.githubusercontent.com/nimsandu/spicetify-bloom/main/install.ps1" | Invoke-Expression
```

**Comment by TheKfcBandit** [comment]
doesn't work for me

**Comment by nimsandu** [comment]
closing issue as completed. thanks for everyone and don't hesitate to open another issue if there is anything wrong. 
enjoy bloom!
