### ISSUE TITLE
Linux installation script doesn't check if Spicetify is installed or not

### ISSUE THREAD

**Issue by windowz414** [nimsandu/spicetify-bloom#119]
This will most probably be a big headache as the installation script would run all the commands blindly without knowing if Spicetify is installed or not, eventually failing.

I'll be opening a new PR regarding this to work around this. My implementation will be doing a check before running anything and, if Spicetify isn't installed, eventually return stop the script right away. This will also reduce system workload if the machine is old enough to barely handle Linux installations.

**Comment by nimsandu** [comment]
also fixed  by @windowz414 trough #120

**Comment by windowz414** [comment]
> also fixed by @windowz414 trough #120

I'm in a PR spree before classes for real. xD

**Comment by nimsandu** [comment]
🙂
