### ISSUE TITLE
Scrollbar does not end properly on the bottom part of the pages

### ISSUE THREAD

**Issue by leonardodafishy** [nimsandu/spicetify-bloom#12]
ISSUE: Whenever I scroll to the bottom most part of the page, the media bar is blocking the bottom portion and does not let me see through.

IMAGE:
![image](https://user-images.githubusercontent.com/70272939/169653130-6f964ec6-89c0-45d7-94ea-38c665c10919.png)
![image](https://user-images.githubusercontent.com/70272939/169653263-ca5a38d9-0cdb-484f-806e-dc83bc92429d.png)

**Comment by stpnwf** [comment]
Yeah, this is not a problem until it _really_ is a problem.
The mobile app has the same floating media bar and it avoids this issue by adding empty space at the bottom of pages. Perhaps the same can be done in bloom to avoid this issue.

**Comment by nimsandu** [comment]
@stpnwf thanx
lets see what can we do

**Comment by nimsandu** [comment]
Fixed in latest version
