### ISSUE TITLE
Linux: Illegal option for command `read`

### ISSUE THREAD

**Issue by windowz414** [nimsandu/spicetify-bloom#121]
The script is invoked with `sh`, which doesn't understand all commands `bash` does. Migration to `bash` will be better since it can understand more extended options than `sh`.

```
sh: 9: read: Illegal option -s
```

I'll open a PR regarding this too.

**Comment by windowz414** [comment]
PR has been merged in. Closing.

**Comment by nimsandu** [comment]
@windowz414 ❤️
