### ISSUE TITLE
Spicetify changes don't get applied in the last before installation ends.

### ISSUE THREAD

**Issue by windowz414** [nimsandu/spicetify-bloom#123]
Spicetify doesn't apply your changes before having it backed up for the first installation, leaving us with this message instead;
```
spicetify v2.14.1
error You haven't backed up. Run "spicetify backup apply".
```

Instead of making the user run this, I'll open a PR that will automatically run this in case of failure to run last command and finish up that way.

**Comment by nimsandu** [comment]
wow you are going to place a new world record ig

**Comment by nimsandu** [comment]
one thing what happened to your twitter account? @windowz414

**Comment by windowz414** [comment]
> one thing what happened to your twitter account? @windowz414

I just renamed it entirely on a new username, nothing special happened.

**Comment by nimsandu** [comment]
oh sorry i got confused 🫠

**Comment by windowz414** [comment]
> oh sorry i got confused 🫠

It's okay, I just DMed on Twitter as well xddd

**Comment by windowz414** [comment]
PR merged. Closing.

**Comment by nimsandu** [comment]
thanks for the issue as well as the fix @windowz414

**Comment by windowz414** [comment]
> thanks for the issue as well as the fix @windowz414

Any time!
