### ISSUE TITLE
[Question] Should we attempt to fix something little Spotify derped for Linux installations along the way on Debian?

### ISSUE THREAD

**Issue by windowz414** [nimsandu/spicetify-bloom#125]
See https://community.spotify.com/t5/Desktop-Linux/The-app-crashes-on-Debian-due-to-HW-acceleration/td-p/5049188

Although Spotify does work properly on all other Linux installations, it returns this error specifically on Debian, which might confuse an end-user who might not think of running Spotify from Terminal.

```
busra@dolunay:~/spicetify-bloom$ spotify
[1104/134732.855556:FATAL:gpu_data_manager_impl_private.cc(447)] GPU process isn't usable. Goodbye.
Trace/breakpoint trap
```

The solution, as suggested in the Spotify Community post I appended on this post, is to append `--no-zygote` flag on Spotify's launcher entry, which is usually located at `/usr/local/share/applications/spotify.desktop`. Keep in mind, this is Debian-specific and doesn't affect Ubuntu AFAIK. So we have the option to ignore Snap installations -- Debian doesn't provide proper support for it anyway.

Should we really implement this (hacky) fix on the installation script? All it takes us to do is a simple command on that `.desktop` file anyway;
```bash
sed -i '/^Exec=/ s/spotify/spotify --no-zygote/'
```

**Comment by nimsandu** [comment]
what if we create a whole new script specially created for Debian and include the script and description in readme?

**Comment by windowz414** [comment]
> what if we create a whole new script specially created for Debian and include the script and description in readme?

Would also work, I just didn't want to hassle with multiple scripts as what we're doing is practically the same on all distros.

**Comment by nimsandu** [comment]
we can include it on a collapsed list which says (special script for Debian users) so normal users won't get confused in my point of view because this is going to be a extra functionality for specific set of users who uses Debian

**Comment by windowz414** [comment]
> we can include it on a collapsed list which says (special script for Debian users) so normal users won't get confused in my point of view because this is going to be an extra functionality for specific set of users who uses Debian

Oh now that's a good solution. I'm already working on it! :P

**Comment by windowz414** [comment]
PR merged. Issue closed.
