### ISSUE TITLE
The volume and music time sliders not appearing properly 

### ISSUE THREAD

**Issue by HubCode07** [nimsandu/spicetify-bloom#129]
For some reason, when I installed this theme the sliders had a duplicated circle (or slider dot). It is not especially annoying but looks really unappealing when using the slider to move around the music. 

Things to note:

- Running the latest version of Spotify/spicetify (spicetify 2.14.3)
- Installed this theme yesterday 
- 
![image](https://user-images.githubusercontent.com/105132635/204060483-841ffbfa-362c-457b-a37b-f57a4f203129.png)

**Comment by windowz414** [comment]
Can't reproduce the issue. Works all fine OOB on my end.

**Comment by nimsandu** [comment]
@HubCode07 it usually happens when you moved from fluent spicetify to bloom spicetify 

Send us a screenshot of your xpui.js file

We will let you know how to fix it by yourself
(Note: this happens when you haven't properly uninstalled previous versions of bloom or spicetify-fluent or else when you apply the theme wrong)

**Comment by ryanmoz** [comment]
I had this issue. Very easy to fix. I had previous installed Fluent and the Fluent.js was still in the config even after uninstalling. Just remove that as well as deleting the fluent folder from your Themes folder. Make sure you have 

**[Patch]
xpui.js_find_8008 = ,(\w+=)32,
xpui.js_repl_8008 = ,${1}56,**

This fixed everything for me.

**Comment by nimsandu** [comment]
@ryanmoz Thanks it is the solution

We will wait for @HubCode07 to conform its fixed 

Anyways thanks for your solution @ryanmoz 
And also a special thanks to @windowz414  for quick response for this issue 

You make bloom better!

**Comment by HubCode07** [comment]
[AdditionalOptions]
home_config           = 1
experimental_features = 1
extensions            = fluent.js|bloom.js
custom_apps           = marketplace
sidebar_config        = 1

[Patch]
xpui.js_find_8008 = ,(\w+=)32,
xpui.js_repl_8008 = ,${1}56,

[Setting]
inject_css              = 1
replace_colors          = 1
overwrite_assets        = 1
check_spicetify_upgrade = 0
spotify_path            = C:\Users\nachi\AppData\Roaming\Spotify
current_theme           = bloom
color_scheme            = dark
spotify_launch_flags    = 
prefs_path              = C:\Users\nachi\AppData\Roaming\Spotify\prefs

[Preprocesses]
disable_upgrade_check = 1
disable_sentry        = 1
disable_ui_logging    = 1
remove_rtl_rule       = 1
expose_apis           = 1

; DO NOT CHANGE!
[Backup]
version = 1.1.99.878.g1e4ccc6e
with    = 2.14.3

**Comment by HubCode07** [comment]
[AdditionalOptions]
home_config           = 1
experimental_features = 1
extensions            = fluent.js|bloom.js
custom_apps           = marketplace
sidebar_config        = 1

[Patch]
xpui.js_find_8008 = ,(\w+=)32,
xpui.js_repl_8008 = ,${1}56,

[Setting]
inject_css              = 1
replace_colors          = 1
overwrite_assets        = 1
check_spicetify_upgrade = 0
spotify_path            = C:\Users\nachi\AppData\Roaming\Spotify
current_theme           = bloom
color_scheme            = dark
spotify_launch_flags    = 
prefs_path              = C:\Users\nachi\AppData\Roaming\Spotify\prefs

[Preprocesses]
disable_upgrade_check = 1
disable_sentry        = 1
disable_ui_logging    = 1
remove_rtl_rule       = 1
expose_apis           = 1

; DO NOT CHANGE!
[Backup]
version = 1.1.99.878.g1e4ccc6e
with    = 2.14.3

Also I have deleted fluent on my computer

**Comment by windowz414** [comment]
> And also a special thanks to @windowz414 for quick response for this issue
> 
> You make bloom better!

Any time, @nimsandu! You're the one who made Bloom and so managed to establish this strongly bonded community. I should thank you for that. <3

**Comment by HubCode07** [comment]
I did all of the instructions said above but it did not work for me (it did not fix the problem) here is the screenshot of the file 
![image](https://user-images.githubusercontent.com/105132635/205426099-ab54b3c5-ca9d-4904-a3e5-2be8405ad05c.png)

**Comment by HubCode07** [comment]
Sorry for the wait, here is the text file if you need it (converted file, since GitHub, does not support js files)
[xpui.txt](https://github.com/nimsandu/spicetify-bloom/files/10145763/xpui.txt)

**Comment by HubCode07** [comment]
issue fixed reinstalled Spotify and worked
