### ISSUE TITLE
Issues + suggestions

### ISSUE THREAD

**Issue by stpnwf** [nimsandu/spicetify-bloom#13]
I am loving this theme. Simply gorgeous. Keep up the good work.

## Found some issues:

<details>
    <summary>1. Toggles are all the same color.</summary>
<img src="https://user-images.githubusercontent.com/81482539/169701493-1fe78038-6009-4967-a923-a5314f92bb10.png" width="300">
</details>

<details>
    <summary>2. Playlists names are shown in sidebar instead of cover images</summary>
<img src="https://user-images.githubusercontent.com/81482539/169701526-9ecbdf77-4613-482f-80b3-abb39e636e0d.png">
</details>

## Improvement suggestions:

<details>
    <summary>1. Option to add folder image like dribbblish</summary>
<img src="https://camo.githubusercontent.com/b9baa70caea20d7377421eaf040984669407af46b49050d4fda08faf87764072/68747470733a2f2f692e696d6775722e636f6d2f574751374265762e676966" width="500">
</details>

<details>
    <summary>2. Change play button hover color to accent color</summary>
<img src="https://user-images.githubusercontent.com/81482539/169724065-7041417b-b85b-4c7c-8d8e-92bd971fa069.jpg" width="300">
</details>

<details>
    <summary>3. Change New Playlist, Liked Songs and Your Episode buttons to match the style of Home,Search and Library.</summary>
<img src="https://user-images.githubusercontent.com/81482539/169701526-9ecbdf77-4613-482f-80b3-abb39e636e0d.png">
</details>

<details>
    <summary>4.Change Marketplace icon. Currently it is the same as Library icon.</summary>
<img src="https://user-images.githubusercontent.com/81482539/169725303-a60859ba-d5bd-4481-bffc-d1b6706c7767.jpg">
</details>

<details>
    <summary>5. Change scrollbar in add to playlist dialog</summary>
<img src="https://user-images.githubusercontent.com/81482539/169723753-6ee27212-1673-40a1-a6c5-6b9c2700b453.png" width="500">
</details>

**Comment by nimsandu** [comment]
your suggestions makes it better for us!

**Comment by nimsandu** [comment]
@stpnwf  and also we have fixed 
"2. Change play button hover color to accent color"
issue too

**Comment by nimsandu** [comment]
@stpnwf only remaining suggestions are
"1. Option to add folder image like dribbblish"
"1. Toggles are all the same color"

**Comment by nimsandu** [comment]
@stpnwf today with the merge of #85 by @MGPlayzYT your suggestion to fix all toggles are same color issues has been fixed 

We are always getting better and working hard to deliver the best experience to our users

Only thing left is folder image suggestion,but we haven't planned it yet so im closing this issue now as we completed every feature requested by you other than folder image feature 

Hope you will enjoy the theme which made better by your suggestions 

I would like to thank everyone who contributed 

Enjoy the calmness of BLOOM!

Thanks for reaching out
