### ISSUE TITLE
Icons of playlist not displaying correctly

### ISSUE THREAD

**Issue by Crushoverride007** [nimsandu/spicetify-bloom#131]
is there a possibility, of how to fix this problem. cause it seems like i am the only person with this issue

![Screenshot 2022-12-12 at 22 29 37](https://user-images.githubusercontent.com/45631812/207158615-b3045022-1544-40f1-93d9-8a13861bc786.png)

**Comment by Crushoverride007** [comment]
I've done some research and i found a hot fix for the time being, for anyone that might have the same issue in the future, here's a quick step
- on the ~/.config/spicetify/Themes/Bloom/user.css ive added max-width:100% into the following line
![SCR-20221212-w3d-2](https://user-images.githubusercontent.com/45631812/207165791-5518dd17-f4ef-4cc5-ba22-24a63744c7ed.png)
- here's the final result of applying new changes
![Screenshot 2022-12-12 at 23 09 31](https://user-images.githubusercontent.com/45631812/207165864-154748af-8962-4a34-97ee-2648959077ce.png)

**Comment by nimsandu** [comment]
@Crushoverride007 sorry for the incontinence and thanks for the fix
it seems we can merge this as a fix
can you open a pr?

**Comment by PrincessAkira** [comment]
> is there a possibility, of how to fix this problem. cause it seems like i am the only person with this issue
> 
> ![Screenshot 2022-12-12 at 22 29 37](https://user-images.githubusercontent.com/45631812/207158615-b3045022-1544-40f1-93d9-8a13861bc786.png)

Ur not the only one. But mine is kinda different in nature.
![image](https://user-images.githubusercontent.com/45071533/207376573-f4134415-e5fb-4db5-9773-891f2e1e2669.png)
When i scroll down it looks like this.

**Comment by nimsandu** [comment]
the problem is mine work fine🥲

**Comment by windowz414** [comment]
Can't reproduce this issue here either. ;w;

**Comment by Crushoverride007** [comment]
@windowz414 I think, its an installation problem. Ive an m1 so i think somethings gone wrong while installing spicetify

**Comment by Crushoverride007** [comment]
> the problem is mine work fine🥲

can you leave out your source folder of spicetify?

**Comment by nimsandu** [comment]
> > the problem is mine work fine🥲
> 
> 
> 
> @nimsandu can you leave out your source folder of spicetify?

I am not quite sure I understood what you said

**Comment by Crushoverride007** [comment]
i meant your configuration of the spicetify in ~/.config/spicetify

**Comment by Crushoverride007** [comment]
@nimsandu thank you, dont worry about it 👍🏻
