### ISSUE TITLE
Design breakages after merging one of recent PRs

### ISSUE THREAD

**Issue by AlleBoy08** [nimsandu/spicetify-bloom#138]
So when trying to connect to another device like a Google Home device, the UI is basically broken, nothing shows up other than an text saying "Select another device" outside of the UI. 
![image](https://user-images.githubusercontent.com/81284701/208247518-785208de-7007-453a-b1b8-ad9ce233adfc.png)

**Comment by nimsandu** [comment]
We will look into this issue asap
Sorry for the inconvenience 
And thanks for reaching out

**Comment by windowz414** [comment]
Happens after one of the PRs, which I didn't have time to look into.

**Comment by windowz414** [comment]
The same PR also causes this design inconsistency on Linux:

![image](https://user-images.githubusercontent.com/39265461/208593002-dfeeba51-776b-4688-8372-efd072d159d2.png)

So I suggest we change the subject to "Design breakages after merging one of recent PRs" instead for better traceability.

**Comment by nimsandu** [comment]
@windowz414 Ill go through all the recent commits and check what we missed. Asap
Thanks

**Comment by windowz414** [comment]
@nimsandu, take your time, no need to rush. <3

**Comment by L3-N0X** [comment]
Im experiencing the same error and after reading the answers here, I looked in the commits and clicked on a random one, a3db56fae6e586446ba01cc6871d4516cba90a73 and saw the merge of the pull-request #135 and since it said something with max-width in user.css I deleted this line and now the devices container just works fine!

**Comment by windowz414** [comment]
> Im experiencing the same error and after reading the answers here, I looked in the commits and clicked on a random one, [a3db56f](https://github.com/nimsandu/spicetify-bloom/commit/a3db56fae6e586446ba01cc6871d4516cba90a73) and saw the merge of the pull-request #135 and since it said something with max-width in user.css I deleted this line and now the devices container just works fine!

Time to turn it into a PR. Thanks @L3-N0X!

**Comment by L3-N0X** [comment]
Today I tried to fix it on an other device and I applied the Bloom theme with only this one line deleted, and then the error still existed, so I added width: 200px; in the user.css for the device container. Then everything was fine, but I'm not sure if this is necessary because applying the theme was buggy for me because I had installed it twice, from marketplace and manually. So if just deleting the line is not helping, this may be changed somehow too. On the first device I may also had the line with width:200px; still in the user.css

**Comment by nimsandu** [comment]
@L3-N0X  @windowz414 would you look into #147 pr

He referenced another commit 

Please

**Comment by L3-N0X** [comment]
I think its the same commit, one of it is the merge of this and the other one is just the fix. Anyways both solutions talk about the same line and same fix in the user.css

**Comment by nimsandu** [comment]
@L3-N0X thanks a lot.
we will merge it once @windowz414 conform the validity.
i'm not going to take any risks now🥲

**Comment by nimsandu** [comment]
@windowz414 oh sorry, i forgot about this issue page. i closed #145 . now we can rename this issue as linux play/pause button issue right?

**Comment by windowz414** [comment]
> @windowz414 oh sorry, i forgot about this issue page. i closed #145 . now we can rename this issue as linux play/pause button issue right?

I...guess so. Do whatever you feel is right, @nimsandu.

**Comment by nimsandu** [comment]
> > @windowz414 oh sorry, i forgot about this issue page. i closed #145 . now we can rename this issue as linux play/pause button issue right?
> 
> 
> 
> I...guess so. Do whatever you feel is right, @nimsandu.

Issue is better in current topic. @windowz414 I guess

**Comment by windowz414** [comment]
> @windowz414 hello! are we ready to close this issue?

@nimsandu, unfortunately no, it still happens on Linux...

**Comment by SunsetTechuila** [comment]
> @nimsandu, unfortunately no, it still happens on Linux...
What exactly is the problem? Is it the buttons or the devices menu?

**Comment by windowz414** [comment]
> > @nimsandu, unfortunately no, it still happens on Linux...
> 
> What exactly is the problem? Is it the buttons or the devices menu? All buttons issues should be fixed with [this pr](https://github.com/nimsandu/spicetify-bloom/pull/232)

https://github.com/nimsandu/spicetify-bloom/issues/138#issuecomment-1358869901

I'll try installing Bloom on my Chromebook's Linux Development Environment and see how it rolls.

**Comment by windowz414** [comment]
![image](https://user-images.githubusercontent.com/39265461/231999744-03bc6871-8d95-4838-8356-ba74ecc99eee.png)

Yep, seems all fine now, safe to close this issue.

**Comment by nimsandu** [comment]
> ![IMG_2023-04-14-12-08-19-646](https://user-images.githubusercontent.com/39265461/232000231-c6f6cc78-cece-4c8d-af52-82c8d1ea6eee.jpg)
> 
> Yep, seems all fine now, safe to close this issue. (Sorry, I couldn't take proper screenshot on my Chromebook.)

its alright @windowz414 !
thanks @SunsetTechuila
