### ISSUE TITLE
Spotify doesn't work after applying theme

### ISSUE THREAD

**Issue by pronoy2108** [nimsandu/spicetify-bloom#14]
![image](https://user-images.githubusercontent.com/83197609/170833514-8d3aae6b-7fd1-4996-9010-cd1366d952cc.png)

**Comment by nimsandu** [comment]
that's not a theme related bug @pronoy2108 even i experienced that in the past 
![image](https://user-images.githubusercontent.com/57834844/170856933-c24561d9-445c-4a6e-8ef9-93bd94dcf1bf.png)
what you need to do is completely remove Spotify and bloom theme  
and run this command to update spicetify
```
spicetify upgrade
```
and re install the theme using this command
```powershell
Invoke-WebRequest -UseBasicParsing "https://raw.githubusercontent.com/nimsandu/spicetify-bloom/main/install.ps1" | Invoke-Expression
```
