### ISSUE TITLE
Made for Us Tab is Inconsistent with Other Playlists

### ISSUE THREAD

**Issue by windowz414** [nimsandu/spicetify-bloom#140]
Image is self-explanatory, nothing else to say.

The tab reveals when someone makes a Blend with or if Spotify makes a genre mix for you.

![image](https://user-images.githubusercontent.com/39265461/208594592-fb63f2f6-82a2-4a8c-b594-f529b0a3da69.png)

**Comment by nimsandu** [comment]
@windowz414 We might haven't mapped it into our theme. So we have to add "made for you" section to the css

**Comment by nimsandu** [comment]
Sorry for the late responses 
And thanks for what you are doing to make our theme way better @windowz414

**Comment by windowz414** [comment]
> @windowz414 We might haven't mapped it into our theme. So we have to add "made for you" section to the css

@nimsandu, hmm, I'll see what it's mapped to whenever I turn my laptop back on and report back.

**Comment by windowz414** [comment]
> Sorry for the late responses 
> And thanks for what you are doing to make our theme way better @windowz414 

@nimsandu, any time! It's just something I think is right to do for a kind developer like you. <3

**Comment by nimsandu** [comment]
@windowz414 ❤️ thanks

**Comment by windowz414** [comment]
Apparently this issue is a little abandoned.

Instead of bumping it, I'll close it, not because it's abandoned but because Made for Us tab has been removed from my side long ago.

If someone else is facing it, ping me and I'll reopen the issue.

**Comment by nimsandu** [comment]
@windowz414 sorry for not paying attention about this issue. i didn't have a made for us tab to experiment with 🥲.

**Comment by windowz414** [comment]
> @windowz414 sorry for not paying attention about this issue. i didn't have a made for us tab to experiment with 🥲.

It's fine @nimsandu, I lost that tab too anyway. xD

**Comment by nimsandu** [comment]
> > @windowz414 sorry for not paying attention about this issue. i didn't have a made for us tab to experiment with 🥲.
> 
> It's fine @nimsandu, I lost that tab too anyway. xD

🤣 thanks
