### ISSUE TITLE
seek and volume icon bugged

### ISSUE THREAD

**Issue by TukangM** [nimsandu/spicetify-bloom#151]
![image](https://user-images.githubusercontent.com/91467886/216742384-fdc0af28-421e-4699-96e8-b40afa802d62.png)
i just install bloom from marketplace. but when i install with [automated powershell cmdline](https://github.com/nimsandu/spicetify-bloom#automated-installation) this bug / icon are not buggy

**Comment by TukangM** [comment]
oh. it was fixed. i just reinstall all spicetify and was fixed. but not the default theme 
![image](https://user-images.githubusercontent.com/91467886/216744010-a63f32be-2a5b-44ed-8d34-539ed6adb43b.png)

**Comment by TukangM** [comment]
![image](https://user-images.githubusercontent.com/91467886/216772678-01cb5217-c797-4fef-a3fd-f6101e31c670.png)

the seek and volume are buggy again

**Comment by nimsandu** [comment]
can you kindly send us a screenshot of your xpui file
We will tell you how to get it fixed @TukangM

**Comment by TukangM** [comment]
```
[Setting]
color_scheme            = dark
replace_colors          = 1
overwrite_assets        = 1
spotify_launch_flags    = 
check_spicetify_upgrade = 0
spotify_path            = C:\Users\lenovo\AppData\Roaming\Spotify
prefs_path              = C:\Users\lenovo\AppData\Roaming\Spotify\prefs
current_theme           = marketplace
inject_css              = 1

[Preprocesses]
disable_ui_logging    = 1
remove_rtl_rule       = 1
expose_apis           = 1
disable_upgrade_check = 1
disable_sentry        = 1

[AdditionalOptions]
home_config           = 1
experimental_features = 1
extensions            = bloom.js
custom_apps           = marketplace
sidebar_config        = 1

[Patch]
xpui.js_find_8008 = ,(\w+=)32,
xpui.js_repl_8008 = ,${1}56,

; DO NOT CHANGE!
[Backup]
version = 1.2.4.912.g949d5fd0
with    = 2.16.1
````

**Comment by TukangM** [comment]
umm. the marketplace updated to 0.8.5. and the seek and volume became buggy again. but i `spicetify apply` again that was fixable

**Comment by nimsandu** [comment]
- @TukangM These kind of Issue ussual occurs when you use marketplace version. With each crash or update marketplace automatically reapply theme and sometimes it cause theme to apply twice and then these type of things happens. My personal recommendation for you is to completely remove marketplace version and apply script version instead. It will help you to keep blooming without any confusions
Thanks 
Enjoy bloom

**Comment by nimsandu** [comment]
@rashil2000 well in this case you have moved from fluent recently
![image](https://user-images.githubusercontent.com/57834844/217855525-b1de0d20-1f70-443b-b3f1-f5f3a223f561.jpeg)

Removing highlighted part (only fluent.js)
Will fix the issue
After removing tun spicetify apply command 

You might good to go

**Comment by nimsandu** [comment]
![image](https://user-images.githubusercontent.com/57834844/217856210-f68694e3-c90c-488a-a9d4-93aac1c0f319.png)

@rashil2000 I meant this highlighted part

**Comment by rashil2000** [comment]
Thank you, that did it!
