### ISSUE TITLE
Conflict with the sidebar

### ISSUE THREAD

**Issue by teddythinh** [nimsandu/spicetify-bloom#153]
So I have a bug that the texts conflict with the sidebar.
I am using **Spotify for Windows v1.2.4.912.g949d5fd0** and **Spicetify v2.16.1**

![image](https://user-images.githubusercontent.com/85171754/218782289-4ee16a31-885f-470b-8c92-b260b15d69ff.png)

**Comment by windowz414** [comment]
I think you installed it from Marketplace or did something wrong during the process. Use the script in this repo for proper installation.

**Comment by nimsandu** [comment]
@teddythinh 
well, we can't find this issue on our devices. 
![image](https://user-images.githubusercontent.com/57834844/218960991-4a3a7221-bc83-4af1-b4b2-3434c2dae222.png)
we recommend you to uninstall spicetify and spotify completely and re install spotify and then apply the theme using automated installation script. 

## Automated Installation

### Windows (Powershell)

```powershell
Invoke-WebRequest -UseBasicParsing "https://raw.githubusercontent.com/nimsandu/spicetify-bloom/main/install.ps1" | Invoke-Expression
```

after proceeding following steps let us know what happened.
if it does not fix the issue, don't hesitate to reach us again
thanks.

**Comment by teddythinh** [comment]
I reinstalled Spotify and found that I also use SpotX with Spotify, which causes this issue. Thanks @windowz414 and @nimsandu.

**Comment by windowz414** [comment]
Glad to have helped.

**Comment by nimsandu** [comment]
@teddythinh Our pleasure 
Don't hesitate to reach us out again if you face any issues in  the future 

And @windowz414 thanks for helping me

**Comment by windowz414** [comment]
> And @windowz414 thanks for helping me

My pleasure @nimsandu!

**Comment by teddythinh** [comment]
Hi there,

I have updated my Spotify to **version 1.2.6.863.ge7902f05 for Windows** today. However, I have uninstalled the SpotX extension, yet I am still having trouble with the sidebar UI. Whenever I expand my library, the text overlaps with other elements, causing a conflict in the UI.

![image](https://user-images.githubusercontent.com/85171754/222880712-37e8f6b9-87f6-4aa4-aaf6-c4702bbf03d7.png)

And when I collapse the library, it's okay again.

![image](https://user-images.githubusercontent.com/85171754/222880955-046eae9f-f4d5-4cef-b7bf-82230bc4d4cc.png)


These are my versions of Spotify and Spicetify.
![image](https://user-images.githubusercontent.com/85171754/222880567-bc449f9e-a108-4474-b935-01167b84e159.png)

**Comment by nimsandu** [comment]
im not quite sure what you meant. but these types of icons are nor expected with bloom. so what i recommend you is to run the script again and let us know what happened 
based on that i might be able to provide you a proper answer

**Comment by SunsetTechuila** [comment]
@teddythinh as a temporary solution, disable `Enable Your Library Х view of the left sidebar` in the spicetify experimental features menu

**Comment by nimsandu** [comment]
> @teddythinh as a temporary solution, disable `Enable Your Library Х view of the left sidebar` in the spicetify experimental features menu

@teddythinh as @SunsetTechuila mentioned. this happened due to Spotify itself testing a new ui. it doesn't map with our theme. so you have to disable that experimental feature. that is the only solution. you might have figured it out already thanks to sunset

**Comment by SunsetTechuila** [comment]
I fixed the most notable issues in [this](https://github.com/SunsetTechuila/spicetify-bloom/tree/libraryX) branch. It is still far from ideal, but it is already possible to test

**Comment by nimsandu** [comment]
> I fixed the most notable issues in [this](https://github.com/SunsetTechuila/spicetify-bloom/tree/libraryX) branch. It is still far from ideal, but it is already possible to test

ill test it out @SunsetTechuila

**Comment by SunsetTechuila** [comment]
the branch is almost ready for release, feedback needed

**Comment by Tezz95** [comment]
After the latest update, I found too many problems.
_1. Sidebar Icon not properly showing.
2.  Playlist and Album Images are cropped in Sidebar.
3. Album Cover misplaced in Expanded mode.
4. Account info icon is misplaced (this issue is old, it was also in the previous version)_

This is the collapsed state
![Collapsed](https://github.com/nimsandu/spicetify-bloom/assets/133680165/735ba794-992a-4428-afb7-8c2379f7f0a1)

This is the Expanded State
![Expanded](https://github.com/nimsandu/spicetify-bloom/assets/133680165/ba1cb25e-44e5-49b9-b731-6ecca6f9b38b)

Here are the version details 
![Info](https://github.com/nimsandu/spicetify-bloom/assets/133680165/9df27db7-a92e-4049-9c40-e53639757e2a)
