### ISSUE TITLE
Full screen buttons too close from volume bar

### ISSUE THREAD

**Issue by Yashirow** [nimsandu/spicetify-bloom#159]
Hi, I think the full screen buttons (official and Full screen extension) are too close from volume bar and a bit misaligned, might be a great idea to move them a bit to the right and bottom ?

Both active :
![image](https://user-images.githubusercontent.com/100087778/219393635-045abbf8-c73e-400b-b9e7-26f7b2d64827.png)
Only the Full screen extension :
![image](https://user-images.githubusercontent.com/100087778/219393852-50e9fd01-28e0-48f8-b3f3-a4c7c46d247d.png)

**Comment by Yashirow** [comment]
Edit : Might be due to the screen resolution ? This bug appear on one of your screenshot but not on another.

Misaligned :
![image](https://user-images.githubusercontent.com/100087778/219395208-27b9f9bb-c0ff-43d8-a63b-6144fea92290.png)

Not misaligned :
![image](https://user-images.githubusercontent.com/100087778/219395179-9c669cb1-db0d-46f8-b4da-5bfa587649f1.png)

**Comment by nimsandu** [comment]
@Yashirow Yap it's misaligned we got to fix that
Ill do it and let you know 
Thanks

**Comment by nimsandu** [comment]
this issue fixed trough #161 
@Yashirow conform this fix and let me know please!

**Comment by Yashirow** [comment]
Works perfectly with only the Full screen button from the extension but the official one is still misaligned (with the extension or without). Personally I only use the extension so it's okay.

Only extension :
![image](https://user-images.githubusercontent.com/100087778/219667073-fee24a4a-6671-4b2d-9801-28a13b20329c.png)

Official + extension :
![image](https://user-images.githubusercontent.com/100087778/219667234-cf6f4451-860b-4b4e-a3bd-4b4a16743cb3.png)

Only official :
![image](https://user-images.githubusercontent.com/100087778/219668366-e5a843a4-5224-4170-841d-c1a31086e007.png)

**Comment by Yashirow** [comment]
I use this CSS line to hide the official button : `button[title="Full screen"] { display: none !important; }`
Maybe replacing the `display: none !important` with `padding: x !important` and tweaking the x value could work ?

**Comment by nimsandu** [comment]
@Yashirow Ill Check it out thanks for your help

**Comment by nimsandu** [comment]
@Yashirow  can you check the existence of this issue and let me know?
(check after running the installation script again)

**Comment by Yashirow** [comment]
It's still the same as before
![image](https://user-images.githubusercontent.com/100087778/220930072-75e351f6-0f26-4dc1-830a-ae596545e2ad.png)

**Comment by SunsetTechuila** [comment]
@Yashirow try [this](https://github.com/SunsetTechuila/spicetify-bloom/blob/fs-test/user.css) file please

**Comment by Yashirow** [comment]
Fixed with this user.css @SunsetTechuila 
![image](https://user-images.githubusercontent.com/100087778/231522829-b8e78348-7b07-4fdc-ae7f-460a033900a7.png)

**Comment by SunsetTechuila** [comment]
only extension and only official too?

**Comment by Yashirow** [comment]
Only extension was working before and is still working
Only official also work now
