### ISSUE TITLE
Theme is broken in latest Spotify

### ISSUE THREAD

**Issue by lemonbigbig** [nimsandu/spicetify-bloom#16]
![image](https://user-images.githubusercontent.com/42226640/171589431-0d8500a4-79d2-4a83-ae77-eba4c54f8e51.png)
![image](https://user-images.githubusercontent.com/42226640/171589531-c9d8fea7-0e4d-48e1-aeca-2f116b1d3972.png)
![image](https://user-images.githubusercontent.com/42226640/171590546-8ae14fb6-c7b3-4b4f-a8de-157f7a6a2449.png)
![image](https://user-images.githubusercontent.com/42226640/171592154-87cf8969-79c7-4fd2-a783-c8939d711e46.png)

-  First, the buttons of the playback control bar are lost, and BLUR has disappeared;

- Second, the lyrics page will scroll the entire page, and this rolling is irreversible. It can only restore the page by switching the song;

- Third, Light color scheme is almost unavailable. The color of most components is the same as the background color;

- Fourth, the album pictures of the playback control bar cannot be enlarged. Click the amplifier's album interface to be deformed and cannot be recovered;

- Fifth, the elements of the page will be blocked by the playback control bar and cannot be used

**Comment by nimsandu** [comment]
can you mention your spicetify version 
if its below 2.10 
 updating spicetify must fix the issue

**Comment by lemonbigbig** [comment]
> can you mention your spicetify version 
> if its below 2.10 
>  updating spicetify must fix the issue

I am currently using spicetfiy version 2.10.1 and Spotify 1.86

**Comment by nimsandu** [comment]
oh!
lets see what we can do to fix that

**Comment by lemonbigbig** [comment]
> Thank you @nimsandu for hard work, but i also had to downgrade to Spotify 1.1.79 for items to be displayed correctly.Also one more question, how to get light theme like @lemonbigbig ?

`spicetify config color_scheme light`

**Comment by serycoola** [comment]
Hi @lemonbigbig what did you change in the CSS to fix the transparency and the buttons? I am having the same issue for the past few days and didn't manage to fix anything. I found that there are 2 classes which upon removal restores the default Spotify buttons, but whatever I tried, I couldn't get the themed buttons to work. And neither was I able to fix the transparency. Do you use the version of the theme installed through powershell, or through the marketplace? Because I noticed that the marketplace theme is completely borked (if the extensions.js file exists in the spicetify-marketplace folder), however that version has transparency...

**Comment by PushaG** [comment]
What other bugs are there? it looks fine from pictures you uploaded.BTW will you be pushing it soon?

**Comment by Sgpilozo** [comment]
> ![imagen](https://user-images.githubusercontent.com/42226640/171677156-63c8b22f-b816-422f-9713-c1e06b0e3bf1.png) ![imagen](https://user-images.githubusercontent.com/42226640/171677292-9066ac29-fbd1-460e-9c48-de049a524511.png) Cambié un poco el archivo CSS para que la floración se ajuste al último Spotify, pero no es suficiente porque no soy lo suficientemente técnico como para hacer todas las correcciones de errores, solo puedo solucionar el problema del esquema.

Excuse me, what did you change to fix it? I have the same problem

**Comment by lemonbigbig** [comment]
![image](https://user-images.githubusercontent.com/42226640/171762526-4bdc4966-81fc-4541-b5a9-ddf1a86df035.png)
![image](https://user-images.githubusercontent.com/42226640/171762631-97e24e40-5594-48e3-bc7a-a0ed23686cb4.png)

The lyrics pages will scroll the whole pages when song is playing, The position of the pages will reversed when next song is played.

**Comment by Sgpilozo** [comment]
> My changes have been uploaded in #17 , BTW, I need some help with the lyrics page and sidebar.

Thank you

**Comment by ps13g** [comment]
My version is completely unusable 
<img width="1512" alt="Screen Shot 2022-06-03 at 10 49 20 AM" src="https://user-images.githubusercontent.com/84423124/171909871-048cc7ee-9da5-4b1b-bcb9-a7222ac9aba8.png">

Im running 1.1.86.857.g3751ee08 and 2.10.1

**Comment by ps13g** [comment]
> Im running 1.1.86.857.g3751ee08 and 2.10.1
I just fixed it but the album art is still off to the side

**Comment by lemonbigbig** [comment]
I also looking a way to sloved that.发件人: ps13g ***@***.***>发送时间: 2022年6月4日星期六 00:55收件人: spicetify-bloom ***@***.***>抄送: me ***@***.***>; mention ***@***.***>主题: Re: [nimsandu/spicetify-bloom] Theme is broken in latest Spotify (Issue #16)

Im running 1.1.86.857.g3751ee08 and 2.10.1

I just fixed it but the album art is still off to the side

**Comment by lemonbigbig** [comment]
I also looking a way to sloved that.

**Comment by lemonbigbig** [comment]
> I also looking for a way to sloved album art issue.

expanded cover issue has been fixed in #21

**Comment by lemonbigbig** [comment]
I also looking a way to sloved that.获取Outlook for Android
