### ISSUE TITLE
Playlist icons not appearing at all

### ISSUE THREAD

**Issue by Novattz** [nimsandu/spicetify-bloom#174]
![Spotify_7YoHgvVzK7](https://user-images.githubusercontent.com/47538996/220625019-2393a543-9ddd-4b58-8054-30c22a33ec0d.png)

Playlist icons do not appear at all and it doesnt matter what i do. I dont know whats causing this issue as it started happening a couple weeks ago. This happens on added playlists that arent even mine aswell.

**Comment by nimsandu** [comment]
@Novattz Well you are in a outdated version of bloom. We have already fixed this issue.
What you have to do is to run installation script again (script in readme)

**Comment by nimsandu** [comment]
@Novattz do you still need help with this issue ?
