### ISSUE TITLE
Things are hidden under play bar and also cant see playlist names.

### ISSUE THREAD

**Issue by Basic6969** [nimsandu/spicetify-bloom#18]
![image](https://user-images.githubusercontent.com/98833613/171994143-be1979d3-debf-4857-95a8-546778319536.png)

**Comment by nimsandu** [comment]
I can fix than but it will effect for the blurry effect

**Comment by Basic6969** [comment]
> I can fix than but it will effect for the blurry effect

any way to keep the mica effect and also make the things above it not below and also what abt play list names.
and original theme dont seem to work ur only works for now (talking abt fluent theme)

**Comment by nimsandu** [comment]
Fixed by @lemonbigbig

**Comment by nimsandu** [comment]
> > I can fix than but it will effect for the blurry effect
> 
> 
> 
> any way to keep the mica effect and also make the things above it not below and also what abt play list names.
> 
> and original theme dont seem to work ur only works for now (talking abt fluent theme)

Fluent theme don't have blurry effect on player so its player bar won't hide things under it
