### ISSUE TITLE
The "About" section on an artist's page appears incomplete.

### ISSUE THREAD

**Issue by kaname-png** [nimsandu/spicetify-bloom#19]
When you view an artist's page and scroll to the bottom to see the "About" section you can see how that section is incomplete because the playback bar is above it.

![Spotify Premium 04_06_2022 10_37_22 a  m](https://user-images.githubusercontent.com/56084970/172016760-206ced5c-0e57-4faf-9504-12674a9e2f35.png)

**Comment by nimsandu** [comment]
That is a fixable issue but it will prevent player bar blur effect

**Comment by lemonbigbig** [comment]
![image](https://user-images.githubusercontent.com/42226640/172529721-af0e251b-1709-47e0-bf49-3817707402a2.png)
I make some change to fix it.

**Comment by nimsandu** [comment]
Again issues fixed by @lemonbigbig
