### ISSUE TITLE
Installation Script (Windows) wrong path

### ISSUE THREAD

**Issue by Satanarious** [nimsandu/spicetify-bloom#2]
What is posted:
`Invoke-WebRequest -UseBasicParsing "https://raw.githubusercontent.com/nimsandu/spicetify-bloom/install.ps1" | Invoke-Expression`

What should be posted:
`Invoke-WebRequest -UseBasicParsing "https://raw.githubusercontent.com/nimsandu/spicetify-bloom/main/install.ps1" | Invoke-Expression`

**Comment by nimsandu** [comment]
sorry sir
