### ISSUE TITLE
Font isn't the same with sidebar's items

### ISSUE THREAD

**Issue by HuyHung1408** [nimsandu/spicetify-bloom#20]
![image](https://user-images.githubusercontent.com/86362423/172090795-34b68589-d1b1-42af-a0ad-ace9717373c2.png)

**Comment by nimsandu** [comment]
The lyric option is not mapped with spicetify css map so we have to wait until the fix that issue

**Comment by kyrie25** [comment]
FYI, this problem is not fixable with Spicetify CSS map as it is dynamically generated, no solution for now.

**Comment by nimsandu** [comment]
@HuyHung1408 you get what @kyrie25 says right?
so i'm going to close the issue for now 
please open another issue if you find another issue

**Comment by HuyHung1408** [comment]
yup, got it thanks
