### ISSUE TITLE
Sliders icon dot rendered twice

### ISSUE THREAD

**Issue by dannyluck** [nimsandu/spicetify-bloom#207]
As the title says, both of the sliders (volume, song time) have the icon's dot rendered twice.
Image:
![obraz](https://user-images.githubusercontent.com/67912255/222924227-78ea8b28-4c5a-4155-a1b9-0be27681241e.png)

**Comment by nimsandu** [comment]
You either have moved here from fluent or you are using marketplace version. Can you send a screenshot of your about Spotify page with spicetify info expanded.

**Comment by 437kasugano** [comment]
I installed it with the pwsh script, but it didn't applied, so I installed the marketplace version. Where is the about spotify page?

**Comment by SunsetTechuila** [comment]
> Where is the about spotify page?

![image](https://user-images.githubusercontent.com/115353812/223536211-34ea6cc7-6a56-4e5e-8acb-9ce241d6ca25.png)

**Comment by SunsetTechuila** [comment]
> it didn't applied, so I installed the marketplace version

Do `spicetify restore` and try again. If the error repeats, show it

**Comment by 437kasugano** [comment]
![obraz](https://user-images.githubusercontent.com/67912255/223537200-c4bf32d9-f59a-4aa6-a764-29bab5273a43.png)
Did spicetify restore and it didn't help, the issue is still there.

**Comment by 437kasugano** [comment]
I forgot to expand, here
![obraz](https://user-images.githubusercontent.com/67912255/223537379-c4721d8b-ea30-49fe-8e5e-37e007042852.png)

**Comment by SunsetTechuila** [comment]
uninstall Boom from the marketplace, clear the `%AppData%\spicetify\Themes` and `%AppData%\spicetify\Extensions` folders, then reinstall Bloom via PoSh

**Comment by SunsetTechuila** [comment]
the double dot is probably the result of bloom.js being executed twice, locally and from the marketplace

**Comment by PrincessAkira** [comment]
Same  problem. not installed via marketplace and reinstalled fully
