### ISSUE TITLE
"Delete playlist" pop-up white with dark theme

### ISSUE THREAD

**Issue by Yashirow** [nimsandu/spicetify-bloom#209]
The text on the screenshot is in french but it's the "delete from library" pop-up that appear when you want to delete a playlist from the dropdown menu. As you can see I use the monodark theme but the button is still in white.

![image](https://user-images.githubusercontent.com/100087778/223205731-9d03fd7a-0de9-4272-9ca1-f44597b4584e.png)

**Comment by nimsandu** [comment]
@Yashirow are we ready to close this issue

**Comment by Yashirow** [comment]
Yep sure, thanks for the quick fix !
