### ISSUE TITLE
Opening a folder makes my sidebar stuck

### ISSUE THREAD

**Issue by ibimcoll** [nimsandu/spicetify-bloom#214]
After I open and then close a folder, spotify wont let me scroll in the sidebar, unless I open the folder. I can scroll completly fine in any folder but not if  I close a folder again. After opening and then closing, the scrollbar disappears and makes me stuck, so that I can see the first few playlists. I can still open the folder tho, just can't scroll to the playlists at the bottom if a folder is opened.

**Comment by ibimcoll** [comment]
It works now, probably broken bcs it was on the newest spotify version

**Comment by nimsandu** [comment]
thanks for reaching out @ibimcoll 
let us know if you need any further assistance!
