### ISSUE TITLE
play icon in playlist is not changing

### ISSUE THREAD

**Issue by daycheat** [nimsandu/spicetify-bloom#219]
![sc](https://user-images.githubusercontent.com/70588692/227528127-c59cae06-a54b-4b10-a07d-2d5757525af3.png)

play icon is changing in default theme, but not changing in bloom
is it intended?

**Comment by nimsandu** [comment]
Well it supposed to change. 
So we are in an issue.
We will work regarding this asap

**Comment by SunsetTechuila** [comment]
@daycheat could you please confirm that the problem no longer exists?

**Comment by daycheat** [comment]
it seems to be fixed now
nice! i will close issue

**Comment by nimsandu** [comment]
@daycheat thanks
enjoy bloom!
credit @SunsetTechuila
