### ISSUE TITLE
Progress bar's dot isn't rendered at all

### ISSUE THREAD

**Issue by windowz414** [nimsandu/spicetify-bloom#222]
The title is self explanatory.

![image](https://user-images.githubusercontent.com/39265461/229989216-a30de409-acf1-4dd3-8334-12695986802c.png)

**Comment by SunsetTechuila** [comment]
![image](https://user-images.githubusercontent.com/115353812/230118093-51556c75-74ef-4813-a388-dd1401712e4f.png)
![image](https://user-images.githubusercontent.com/115353812/230118275-5aa4e31e-51e0-4c9c-8115-c383b81440d6.png)
works for me

**Comment by nimsandu** [comment]
@SunsetTechuila it doesn't work sometimes!

@windowz414 even i experience this issue sometimes!
closing and reopening the spicetify desktop app fixes this issue. but sometimes it doesn't work either. 
so i'll start working on this issue as soon as possible.

**Comment by SunsetTechuila** [comment]
Never faced. Is it random?

**Comment by windowz414** [comment]
@nimsandu, thanks for the tip on reopening it. Now I don't face it...for now.

@SunsetTechuila yes it's random. But I guess it's reproducible by applying a Spicetify config and so make it restart Spotify.

**Comment by SunsetTechuila** [comment]
> Edit 2: Going full screen causes this issue.
Now it makes more sense. Which extension do you use for full screen?

**Comment by windowz414** [comment]
> > Edit 2: Going full screen causes this issue.
> 
> Now it makes more sense. Do you use spotify built-in fullscreen?

Yes I do.

**Comment by SunsetTechuila** [comment]
using css also looks possible
![image](https://user-images.githubusercontent.com/115353812/230383222-00bd3290-7cfe-46ee-9aa1-035601286824.png)
[Code](https://pastebin.com/kzBeSSRy)
I have no time for it now, but maybe @nimsandu will

**Comment by SunsetTechuila** [comment]
With updated bloom?

**Comment by Yashirow** [comment]
Yep sorry that's fixed

**Comment by windowz414** [comment]
> @windowz414 problem no longer exists?

@SunsetTechuila, I'll check when I get on my laptop.

**Comment by windowz414** [comment]
@SunsetTechuila, it's perfect now. Thanks for contributing to Bloom and fixing this bug!

**Comment by nimsandu** [comment]
@windowz414 @SunsetTechuila i always appreciate you both 😊
