### ISSUE TITLE
Light theme is a little broken

### ISSUE THREAD

**Issue by windowz414** [nimsandu/spicetify-bloom#223]
![image](https://user-images.githubusercontent.com/39265461/230353867-6cb56d53-9e10-4c3d-8fc2-5e712b3b5cc8.png)
![image](https://user-images.githubusercontent.com/39265461/230354131-9b48b168-6323-4677-a09a-e41432a11cf6.png)

**Comment by SunsetTechuila** [comment]
It isn't a little broken, it needs to be completely reworked)

**Comment by windowz414** [comment]
> It isn't a little broken, it needs to be completely reworked)

I was trying to be optimistic xd

**Comment by SunsetTechuila** [comment]
@windowz414 is everything okay now?

**Comment by windowz414** [comment]
> @windowz414 is everything okay now?

Lemme see real quick.

**Comment by windowz414** [comment]
Seems all perfect now, closing.
