### ISSUE TITLE
Progress bar dot is off-centered

### ISSUE THREAD

**Issue by ibzann** [nimsandu/spicetify-bloom#235]
title says everything
![image](https://user-images.githubusercontent.com/55029662/231637389-921caac3-aa02-4293-8ffa-1ffb94e9d1cd.png)
![image](https://user-images.githubusercontent.com/55029662/231637456-470487b6-fc86-40d8-a582-27c968671a50.png)

**Comment by nimsandu** [comment]
@ibzann reach out to us and let us know what happened after updating both spotify and spicetify
i recommend you to run bloom installation script after updating spotify

**Comment by ibzann** [comment]
instead of updating i simply just edited the css, i really wasn't bothered to update spicetify/spotify.
