### ISSUE TITLE
New Spotify Update, New Breakages

### ISSUE THREAD

**Issue by windowz414** [nimsandu/spicetify-bloom#236]
The new update to Spotify broke playlist arts on sidebar and player controls (both in normal and full screen mode).

![image](https://user-images.githubusercontent.com/39265461/231873917-cf309e82-2473-4164-a0a4-daf6b5cb068f.png)

**Comment by SunsetTechuila** [comment]
:)

**Comment by SunsetTechuila** [comment]
Can you show the version btw?

**Comment by windowz414** [comment]
![image](https://user-images.githubusercontent.com/39265461/231992249-46c8b868-b3ea-47e2-9272-fd76312aa123.png)

Yup, updating Spicetify did the trick, thank you for showing your version @SunsetTechuila!
