### ISSUE TITLE
Song stream count is misaligned

### ISSUE THREAD

**Issue by MGPlayzYT** [nimsandu/spicetify-bloom#24]
The song stream count seems to be misaligned, as you can see in the image.
![image](https://user-images.githubusercontent.com/51394649/173525949-b4e25ad8-fd7a-46ae-87a3-76799f041ec6.png)

**Comment by lemonbigbig** [comment]
![image](https://user-images.githubusercontent.com/42226640/173598180-22be610e-d358-47b5-892e-cb7cc420ccf2.png)

**Comment by MGPlayzYT** [comment]
> fix is include in #25

The fix seems to have conflicted with other things
![image](https://user-images.githubusercontent.com/51394649/173776585-5712e3fb-6d14-4954-8bde-04d104fbf009.png)

**Comment by nimsandu** [comment]
@lemonbigbig thanx and sorry for the late
