### ISSUE TITLE
Play button and playlist icons are broken.

### ISSUE THREAD

**Issue by Yashirow** [nimsandu/spicetify-bloom#243]
<details>
<summary>Play button</summary>

![image](https://user-images.githubusercontent.com/100087778/233373932-9dc6bbbb-084a-4a39-a268-9d76041cbf09.png)

</details>

<details>
<summary>Playlist icon missing</summary>

![image](https://user-images.githubusercontent.com/100087778/233374026-2e0c672a-61cc-4451-aa57-bb79e02f8a38.png)

</details>

<details>
<summary>The little bar on currently selected icon is missing too</summary>

![image](https://user-images.githubusercontent.com/100087778/233374312-e83a0594-6cbc-46a7-b76d-b18c37bc295f.png)

</details>

<details>
<summary>Spotify version</summary>

![image](https://user-images.githubusercontent.com/100087778/233374622-b271f2fa-944a-4e98-8944-0125d3b111ec.png)

</details>

**Comment by Yashirow** [comment]
It was indeed an installation problem. uninstalling and reinstalling from the marketplace fixed everything. Sorry for not testing this before opening an issue. Thanks.

**Comment by windowz414** [comment]
> It was indeed an installation problem. uninstalling and reinstalling from the marketplace fixed everything. Sorry for not testing this before opening an issue. Thanks.

You're welcome, glad reinstallation fixed your problem! I hope you enjoy Bloom and keep blooming!

**Comment by nimsandu** [comment]
@windowz414 @SunsetTechuila Thanks for your effort!

@Yashirow Let us know if you get any troubles in future
