### ISSUE TITLE
The pause button is not visible

### ISSUE THREAD

**Issue by GastonKhouri** [nimsandu/spicetify-bloom#249]
![image](https://user-images.githubusercontent.com/68894611/234720394-d253da56-190a-432c-b047-f610986d1196.png)

**Comment by SunsetTechuila** [comment]
Extension issue, reinstall bloom

**Comment by GastonKhouri** [comment]
> Extension issue, reinstall bloom

Solved! Thanks

**Comment by SunsetTechuila** [comment]
Bloom was from the marketplace or local installation?

**Comment by GastonKhouri** [comment]
> Bloom was from the marketplace or local installation?

From the marketplace

**Comment by SunsetTechuila** [comment]
Looks like the marketplace has some difficulties about switching the extension to a new one for an already installed theme
