### ISSUE TITLE
Some broken elements on todays update of Spotify

### ISSUE THREAD

**Issue by cmdshft** [nimsandu/spicetify-bloom#250]
Seems a few elements broke. Re-ran the script twice to be sure, still broken.

![Screenshot 2023-04-27 140135](https://user-images.githubusercontent.com/8571823/234952808-7e71a4eb-6278-4c72-b0c9-ce4e7db8094e.png)
![Screenshot 2023-04-27 140149](https://user-images.githubusercontent.com/8571823/234952819-f82482c4-ed95-4c70-8268-d2cb4822241c.png)

Also, scrolling seems to still be bugged on the playlist bar.

**Comment by SunsetTechuila** [comment]
#249

**Comment by SunsetTechuila** [comment]
Show "About" window

**Comment by cmdshft** [comment]
![image](https://user-images.githubusercontent.com/8571823/235045953-0a7043de-c792-42c1-a4ab-bc4f93cb095c.png)

**Comment by SunsetTechuila** [comment]
Your spicetify is outdated and doesn't support theme extension feature. Update it to the latest [v2.17.2](https://github.com/spicetify/spicetify-cli/releases/tag/v2.17.2) release

**Comment by cmdshft** [comment]
Ah, i see! Thank you! (now just the stuck scrolling is the only issue remaining on this theme)

**Comment by windowz414** [comment]
This is a reminder to y'all: Remember to close the issues once they're resolved. This way we can keep reputation of our theme and have less clutter regarding open issues.

**Comment by nimsandu** [comment]
@windowz414 😊 true!
