### ISSUE TITLE
User dropdown menu is sent backwards

### ISSUE THREAD

**Issue by karimawii** [nimsandu/spicetify-bloom#259]
### I tried using `z-index: 9999;` with a bunch of selectors, I reinstalled the theme multiple times, it just doesn't want to get in front of the main page, this issue doesn't happen when I disable the theme.

![image](https://github.com/nimsandu/spicetify-bloom/assets/69881381/715ce3a8-5e54-493f-b514-e60db5c25602)
![Spotify_hzCL95Yhos](https://github.com/nimsandu/spicetify-bloom/assets/69881381/00f6a4a7-3bdd-4a5b-8d05-7752d7781c1f)

**Comment by karimawii** [comment]
![image](https://github.com/nimsandu/spicetify-bloom/assets/69881381/dd294dca-4865-4778-b653-9245d0fef01d)

There should be bloom.js right?

**Comment by karimawii** [comment]
Oh nvm
![image](https://github.com/nimsandu/spicetify-bloom/assets/69881381/430b3934-ffb3-410c-838f-9d27e8e2b69d)

**Comment by SunsetTechuila** [comment]
Try to backup marketplace data and then reset it

**Comment by karimawii** [comment]
No luck :'(
![image](https://github.com/nimsandu/spicetify-bloom/assets/69881381/5824d441-e8e8-4b95-a930-7065588e80a6)

**Comment by SunsetTechuila** [comment]
Pretty interesting
`spicetify restore backup apply` ?

**Comment by karimawii** [comment]
I did just update Spotify, but I don't know if that's the issue, let me try

**Comment by karimawii** [comment]
Yeah, still
![image](https://github.com/nimsandu/spicetify-bloom/assets/69881381/3b4dc846-df7d-49bc-ad57-2921dd23edd5)

**Comment by SunsetTechuila** [comment]
open menu, then use copy(document.documentElement.outerHTML) command in devtools console, paste it to pastebin and sent me link

**Comment by SunsetTechuila** [comment]
> No luck :'(

Are all these extensions installed from the marketplace?

**Comment by karimawii** [comment]
Yes

**Comment by SunsetTechuila** [comment]
> this issue doesn't happen when I disable the theme

does it keep appearing right after user-widget box element? it should be the very last element in the DOM

**Comment by SunsetTechuila** [comment]
should be fixed now, but it is strange

**Comment by karimawii** [comment]
Yeah, that fixed it, weird indeed 🤔.

**Comment by SunsetTechuila** [comment]
e1b93092d443a6ae61d01911331867ac9aca7f43
