### ISSUE TITLE
"Add to playlist" button in right-click menu is broken

### ISSUE THREAD

**Issue by Insane-Owl** [nimsandu/spicetify-bloom#260]
Right-clicking a song and selecting "Add to playlist" does nothing. Dragging the song into the playlist works fine, it's just the right-click menu button that doesn't work.

https://github.com/nimsandu/spicetify-bloom/assets/78328941/ca330361-b39e-42ba-bbf5-c879081072d1

**Comment by SunsetTechuila** [comment]
Are you sure this is the theme issue?

**Comment by Insane-Owl** [comment]
> Are you sure this is the theme issue?

Yes, it works how it's supposed to when the theme is removed.

**Comment by Insane-Owl** [comment]
oops, didn't mean to close

**Comment by SunsetTechuila** [comment]
@Insane-Owl works for me now
