### ISSUE TITLE
Visual Bug's

### ISSUE THREAD

**Issue by J-Ciro** [nimsandu/spicetify-bloom#263]
Theres a lot of visual bugs in a clean install of spotify and specify
![image](https://github.com/nimsandu/spicetify-bloom/assets/37349818/373f6bba-2253-450a-bd82-e30c99ad3591)

**Comment by SunsetTechuila** [comment]
provide info about: theme installation type, Spotify/Spicetify version, OS

**Comment by SunsetTechuila** [comment]
and judging by the screenshot, you just have two themes installed at once, check that

**Comment by windowz414** [comment]
Sometimes happens when you install Spicetify over an older version of Spotify. Wait for Spicetify to be updated.
