### ISSUE TITLE
Full Screen Display extension not clickable

### ISSUE THREAD

**Issue by 007-Tommy** [nimsandu/spicetify-bloom#264]
![image](https://github.com/nimsandu/spicetify-bloom/assets/66992279/ab78eeff-c5dd-4570-99ef-8f3aea04aaf9)

Hello, it's hard to show on an image but the full screen display button is not clickable and does not show the clickable cursor when hovered over

PS: I love everything else about this theme, thank you so much for creating this :)

**Comment by SunsetTechuila** [comment]
hello, glad you like the theme!
