### ISSUE TITLE
Now playing bar styling broken for enhanced song with Spotify Genres

### ISSUE THREAD

**Issue by noaione** [nimsandu/spicetify-bloom#267]
### Did you read the README?

- [X] I have read the README, the theme is installed/configured correctly and the "Troubleshooting" section contains no information related to my problem

### Do you have the latest versions of Spicetify, Spotify and Bloom?

- [X] I'm using the latest versions of Spicetify, Spotify and Bloom

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Is your problem definitely caused by the theme?

- [x] I have checked the app behavior without the theme and it is different
- [ ] I have problem with a theme custom feature

### Environment & Computer Info

```Markdown
- Spotify version: `1.2.11.916`
- Installed from: Spotify site
- Spicetify version: `2.18.1`
- Color scheme: dark
- Extensions: `hidePodcasts.js`, `fixEnhance.js`, `fullAlbumDate.js`, `volumePercentageWrapper.js`, `power-bar.js`, `group-session.js`, `romaji_lyrics.js`, `copytoclipboard2.js`, `romaja_lyrics.js`, `cacheCleaner.js`, `songstats.js`, `spotifyGenres.js`, `imageOpener.js`, `theme.js`
- Custom apps: `marketplace`, `new-releases`, `lyrics-plus`
- Bloom installation method: Marketplace
```

### Description

1. Install `Spotify Genres` extensions (https://github.com/Tetrax-10/Spicetify-Extensions/tree/master/Spotify-Genres)
2. Play any "Enhanced" song
3. See that the styling in the now playing bar is broken

Also tested with master at https://github.com/nimsandu/spicetify-bloom/commit/54e477743701d8d4b8df24d010168c01a0342e2f

### Screenshots

![Screenshot](https://github.com/nimsandu/spicetify-bloom/assets/34302902/4b2ed02f-6355-4f33-9d0b-6c56c3e758fa)

**Comment by SunsetTechuila** [comment]
> I have checked the app behavior without the theme and it is different

No, you haven't
 
![image](https://github.com/nimsandu/spicetify-bloom/assets/115353812/adb4d05f-a07b-40fb-acfe-e95aac2d4914)

**Comment by SunsetTechuila** [comment]
issue should be addressed to the Spotify Genres extension dev
