### ISSUE TITLE
Add support for RTL text in Lyrics

### ISSUE THREAD

**Issue by GameZrush** [nimsandu/spicetify-bloom#268]
### Did you read the README?

- [x] I have read the README, the theme is installed/configured correctly and the "Troubleshooting" section contains no information related to my problem

### Do you have the latest versions of Spicetify, Spotify and Bloom?

- [X] I'm using the latest versions of Spicetify, Spotify and Bloom

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Is your problem definitely caused by the theme?

- [ ] I have checked the app behavior without the theme and it is different
- [X] I have problem with a theme custom feature

### Environment & Computer Info

```Markdown
- Spotify version: 1.2.12.902.g1924b088
- Installed from: Spotify site
- Spicetify version: Spicetify v2.18.1
- Color scheme: Dark
- Extensions: 
- Custom apps: 
- Bloom installation method: Manual Installation
```

### Description

It looks fine in English, But the discord support told me to report it as an issue. please see the video

### Screenshots

https://github.com/nimsandu/spicetify-bloom/assets/99245576/87d11519-0492-4aa2-9d07-466224a71291

**Comment by SunsetTechuila** [comment]
I will add support for rtl text later, for now you can create a snippet with this code: `.lyrics-lyricsContent-lyric {transform: none !important}`
