### ISSUE TITLE
Playlist text and not image

### ISSUE THREAD

**Issue by hapatapa** [nimsandu/spicetify-bloom#27]
![image](https://user-images.githubusercontent.com/68708992/174063864-cb9e311c-351b-4556-8212-605fe0aa5648.png)
Could anyone give me your config-xpui.ini file pls?

**Comment by lemonbigbig** [comment]
problem is fixed in #25   but not merge yet

![](https://user-images.githubusercontent.com/42226640/173617608-29fad95c-f52a-491a-885a-b9ec87bd745b.png)

**Comment by nimsandu** [comment]
@lemonbigbig Sorry brother i was busy thanx for the fix
