### ISSUE TITLE
Icons are not being displayed correctly

### ISSUE THREAD

**Issue by andiricum2** [nimsandu/spicetify-bloom#272]
### Did you read the README?

- [X] I have read the README, the theme is installed/configured correctly and the "Troubleshooting" section contains no information related to my problem

### Do you have the latest versions of Spicetify, Spotify and Bloom?

- [X] I'm using the latest versions of Spicetify, Spotify and Bloom

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Is your problem definitely caused by the theme?

- [X] I have checked the app behavior without the theme and it is different

### Environment & Computer Info

```Markdown
- Spotify version: 1.2.12.902.g1924b088
- Installed from: Spotify site
- Spicetify version: v2.19.0
- Color scheme: dark
- Extensions: Feature shuffle, Song Stats, Adblock, Spicetify-Hide-Podcasts, listPlaylistsWithSong, playlistIntersection, Display full Album date, Spotify Genres, Seek Song, Power bar, Cover Ambience, Copy Lyrics
- Custom apps: The Eternal Jukebox, Statistics, Name That Tune
- Bloom installation method: Spicetify Marketplace
```

### Description

In the main sidebar, where the start, search, library icons are, custom apps icons dont appear as they should.

Only the Eternal Jukebox icon is appearing correctly.

In what I have marked in the image, the first house is the Name That Tune custom app and the one below is statistics custom app.

### Screenshots

![image](https://github.com/nimsandu/spicetify-bloom/assets/62946099/22b1cbc7-bfe5-4669-b7d0-3aff309031e2)

**Comment by SunsetTechuila** [comment]
thanks for the feedback, we will add support soon
