### ISSUE TITLE
Bloom breaks Lyrics-plus full screen feature

### ISSUE THREAD

**Issue by InsrtRandomUserHere** [nimsandu/spicetify-bloom#274]
### Did you read the README?

- [X] I have read the README, the theme is installed/configured correctly and the "Troubleshooting" section contains no information related to my problem

### Do you have the latest versions of Spicetify, Spotify and Bloom?

- [X] I'm using the latest versions of Spicetify, Spotify and Bloom

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Is your problem definitely caused by the theme?

- [X] I have checked the app behavior without the theme and it is different
- [ ] I have problem with a theme custom feature

### Environment & Computer Info

```Markdown
- Spotify version: 1.2.12.902.g1924b088
- Installed from: Spotify site
- Spicetify version: 2.20.0
- Color scheme: Bloom / dark
- Extensions: webnowplaying.js, fullScreenWrapper.js, css-editor.js, theme.js
- Custom apps: marketplace, lyrics-plus
- Bloom installation method: Spicetify Marketplace
```

### Description

Bloom breaks the full screen feature of Lyrics-plus. Lyrics-plus is in full-screen, but the UI is still performing as if it is not in full screen. Below is what it looks like if lyrics-plus is full screened. The UI is also isn't interactable. It does work properly with other themes and no theme

### Screenshots
![Screenshot 2023-06-06 200436](https://github.com/nimsandu/spicetify-bloom/assets/72641014/a0ed5ee2-b78d-474b-8a4e-f62c746eb2c0)

_No response_

**Comment by SunsetTechuila** [comment]
![image](https://github.com/nimsandu/spicetify-bloom/assets/115353812/6b008f8e-219f-4757-8372-436f0fcacee8)
