### ISSUE TITLE
Display issues on artist page

### ISSUE THREAD

**Issue by RhapsodySL** [nimsandu/spicetify-bloom#276]
### Did you read the README?

- [X] I have read the README, the theme is installed/configured correctly and the "Troubleshooting" section contains no information related to my problem

### Do you have the latest versions of Spicetify, Spotify and Bloom?

- [X] I'm using the latest versions of Spicetify, Spotify and Bloom

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Is your problem definitely caused by the theme?

- [X] I have checked the app behavior without the theme and it is different
- [ ] I have problem with a theme custom feature

### Environment & Computer Info

```Markdown
- Spotify version: Spotify for Windows 1.2.13.661.ga588f749
- Installed from: Spotify website
- Spicetify version: Spicetify v2.20.0
- Color scheme: Bloom / dark
- Extensions: bookmark.js, trashbin.js, webnowplaying.js, hidePodcasts.js, QueueTime.js, theme.js
- Custom apps: arketplace, new-releases, lyrics-plus
- Bloom installation method: Spicetify Marketplace
```

### Description

Artist pages have minor display and formatting errors. Here's what I've found.

1. When both the Popular list and Artist's Pick list are present, Artist Pick contents are not formatted properly and do not align with the Popular list to the left of it. The contents are actually directly adjacent to the "Artist pick" text indicating it may not be formatted correctly. [Example here](https://github.com/nimsandu/spicetify-bloom/assets/8369578/0719135c-7ba6-4cc4-9790-63d662f6a5f7). Expected behavior is that the contents of the Artist Pick section would properly align with the Popular section to the left of it.

2. When the Popular list is present but Artist Pick is not, the Popular list does not properly expand to the full window. This is most pronounced when the application is in fullscreen, but occurs even on smaller windows. This is not congruent with Spotify's default behavior, in which it would stretch properly. [Example here](https://github.com/nimsandu/spicetify-bloom/assets/8369578/9a3ad7fd-9a43-4359-a41f-04ab140e39de). This issue actually also affects artists where both the Popular list and Artist Pick are present. [Example here](https://github.com/nimsandu/spicetify-bloom/assets/8369578/aae243c0-123d-4605-bcf3-698b6be5b268). 

3. The "See more" button under the popular list is very difficult to see as it does not contrast well with the background, which doesn't seem intentional. [Example here](https://github.com/nimsandu/spicetify-bloom/assets/8369578/b4264df8-a8fe-48cd-9422-0ff74af27634) (note the bottom left of the image). 

4. This one is more of a personal aside, but I feel that having the green "E" below the song name for explicit songs on the Popular list looks awkward and is grabbing too much attention with that color (I am aware that it uses this color in other places, too, like in album views). Changing the color to something with less "pop" might be good, and would also mirror vanilla Spotify's lower-key way of showing it (which is gray on a black background).

Personally, I also feel like the explicit icon would be better placed elsewhere in the Popular view (and maybe the other views?), like at the start or end of the song name, maybe, but this isn't congruent with Spotify's normal behavior at all so I don't expect anything from this.

**Comment by SunsetTechuila** [comment]
1 and 3 are accepted

**Comment by SunsetTechuila** [comment]
also please use the **Screenshots** section for screenshots

**Comment by RhapsodySL** [comment]
Sorry about the mistake there. That being said, there is still an issue where the Popular list does not properly extend as far as Spotify's would: 

![image](https://github.com/nimsandu/spicetify-bloom/assets/8369578/2171ed4e-177e-4eda-b7be-af34aa98b55b)
![image](https://github.com/nimsandu/spicetify-bloom/assets/8369578/cf73e7c4-a23f-43a2-9c3f-c56edfe2bd01)

**Comment by SunsetTechuila** [comment]
> These are with the window at the same size.

Which exactly?

**Comment by RhapsodySL** [comment]
> > These are with the window at the same size.
> 
> Which exactly?

The specific dimensions appear to be 1589x896. I'm unsure of how to grab the actual size of the window, so I took a window screenshot with ShareX and those are the image dimensions.

**Comment by SunsetTechuila** [comment]
![image](https://github.com/nimsandu/spicetify-bloom/assets/115353812/ac3529e0-0da7-4193-a543-92a3d9394120)
![image](https://github.com/nimsandu/spicetify-bloom/assets/115353812/35ee2e5f-8656-4b68-bc36-2516c8e56c84)
the difference is minimal

**Comment by RhapsodySL** [comment]
That is not representative of how it looks on my end.

![image](https://github.com/nimsandu/spicetify-bloom/assets/8369578/86714319-355f-492a-becb-d24f16fde0d8)

This image is with Spicetify disabled.

**Comment by RhapsodySL** [comment]
It seems like we're seeing different things because I don't have LayoutX rolled out to me while you do, so the alignment is different. If that's the case then I suppose this is the proper implementation, but I do personally feel it would look better stretched across the width (at least on a size like this). Of course, that's just a feature suggestion, not something to be fixed, so it does seem like we're good here.

**Comment by SunsetTechuila** [comment]
Since LibraryX will completely replace the classic mode, which will be cut out in the next month, I will not do anything with it
