### ISSUE TITLE
Bloom does not work with Spotify 1.2.14+

### ISSUE THREAD

**Issue by tejasraman** [nimsandu/spicetify-bloom#278]
### Did you read the README?

- [X] I have read the README, the theme is installed/configured correctly and the "Troubleshooting" section contains no information related to my problem

### Do you have the latest versions of Spicetify, Spotify and Bloom?

- [X] I'm using the latest versions of Spicetify, Spotify and Bloom

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Is your problem definitely caused by the theme?

- [X] I have checked the app behavior without the theme and it is different
- [ ] I have problem with a theme custom feature

### Environment & Computer Info

```Markdown
- Spotify version: 1.2.14.1441 (Windows 11 Pro x64)
- Installed from: Spotify website (EXE)
- Spicetify version: 1.20.1
- Color scheme: Bloom - dark
- Extensions: Adblock
- Custom apps:
- Bloom installation method: Marketplace
```

### Description

- Use Spotify 1.2.14 or newer (it removes the option in experimental to disable new Library X view)
- Install Bloom theme

This makes the Bloom theme unusable to the point where I (tried to) downgrade to 1.12 to use Spotify

### Screenshots

![MZSLNVE2Ns](https://github.com/nimsandu/spicetify-bloom/assets/96961804/2215d42c-707d-4728-baf2-75ac38ab23d2)

**Comment by SunsetTechuila** [comment]
Bloom supports Library X and it is even one of the first themes to have support for Library X. The problem is only present in Spotify 1.2.14, because the indication that Library X is active has been removed.
I'm already working on a fix and will release it soon.
As a temporary solution, you can roll back to version 1.2.13 by installing it at this link: https://upgrade.scdn.co/upgrade/client/win32-x86/spotify_installer-1.2.13.661.ga588f749-4064.exe

**Comment by tejasraman** [comment]
> Bloom supports Library X and it is even one of the first themes to have support for Library X. The problem is only present in Spotify 1.2.14, because the indication that Library X is active has been removed. I'm already working on a fix and will release it soon. As a temporary solution, you can roll back to version 1.2.13 by installing it from this link: https://upgrade.scdn.co/upgrade/client/win32-x86/spotify_installer-1.2.13.661.ga588f749-4064.exe

Already tried 1.2.13. I’ll try it again. Thanks so much @SunsetTechuila

**Comment by tejasraman** [comment]
> 1.2.13 definitely works fine with Bloom

Ok, l'll try again. :)

**Comment by tejasraman** [comment]
an update @SunsetTechuila
![ls0GjJeZBv](https://github.com/nimsandu/spicetify-bloom/assets/96961804/51f78408-1f54-495d-b358-0f775634f8b3)

**Comment by SunsetTechuila** [comment]
The question is whether it has such a setting at all.
Assuming the interface is broken, there shouldn't be one. But I know for sure that it should be, as I myself was on this version and everything worked fine, the problems began only with 1.2.14, in which this setting was removed along with the ylx indication

**Comment by SunsetTechuila** [comment]
#277
he has the same version, but the navbar is ok as you can see

**Comment by tejasraman** [comment]
> #277
> 
> he has the same version, but the navbar is ok as you can see 

The sidebar there seems to be the collapsed sidebar (which works fine except it gets covered by the top bar sometimes)

**Comment by tejasraman** [comment]
> Can you try disabling LibraryX from experimental settings?

It was there when I used 1.2.12 but not in 1.2.13

**Comment by SunsetTechuila** [comment]
by mistake
