### ISSUE TITLE
Weird line through the top of the UI

### ISSUE THREAD

**Issue by TheStupidOneHere** [nimsandu/spicetify-bloom#280]
### Did you read the README?

- [X] I have read the README, the theme is installed/configured correctly and the "Troubleshooting" section contains no information related to my problem

### Do you have the latest versions of Spicetify, Spotify and Bloom?

- [X] I'm using the latest versions of Spicetify, Spotify and Bloom

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Is your problem definitely caused by the theme?

- [X] I have checked the app behavior without the theme and it is different
- [ ] I have problem with a theme custom feature

### Environment & Computer Info

```Markdown
- Spotify version:1.2.8.923.g4f94bfOd
- Installed from: Spotify site
- Spicetify version:Spicetify v2.17.O
- Color scheme: dark
- Extensions: adblock.js, fullAppDisplayMod.js, spotifyGenres.js, spotifyBackup.js,
fullScreenWrapper.js, savePlaylistsWrapper.js, romaji_lyricsjs, skip-song-part.js, romaji-
convert.js, songwhip.js, beautiful-lyrics.js, made-for-you-shortcut.js, CoverAmbience.js,
theme.js
- Custom apps:marketplace, lyrics-plus, taste
- Bloom installation method: Spicetify Marketplace
```

### Description

The theme has this visual glitch on all pages
It is a line on the top half of the UI

Another issue is with the playlist list in the bottom left, it is really small and squished for some reason
I have tried installing the patch, removing custom apps, snippets and extensions to no avail

I am extremely sorry if i have seemed to miss something, please help me through this

### Screenshots

![image](https://github.com/nimsandu/spicetify-bloom/assets/71955577/0fd614aa-4b74-41cf-9132-43e8a4ca1d83)

**Comment by SunsetTechuila** [comment]
> I'm using the latest versions of ... Spotify
No, you don't. Update it or use the [legacy](https://github.com/nimsandu/spicetify-bloom/tree/legacy) branch (unsupported)

**Comment by SunsetTechuila** [comment]
In Spotify version 1.2.14, not only has the classic theme been cut, but also the indication that a new theme is active. Since it is now problematic to identify the active theme, only Library X support remains.
For those who don't want to stay on the old theme - use the [legacy branch](https://github.com/nimsandu/spicetify-bloom/tree/legacy) (unsupported).

**Comment by Hi-ImKyle** [comment]
I have this issue on 1.2.14 but you say it should only exist on anything less than that. So now what?

**Comment by SunsetTechuila** [comment]
you probably restored old spotify files
install the newest spotify over the current one and run `spicetify backup apply`

**Comment by Hi-ImKyle** [comment]
Good god you were fast. Thanks, that command is in my history but maybe I'm just confusing it with another time I did it. Fixed <3
