### ISSUE TITLE
Line covering the heading

### ISSUE THREAD

**Issue by matej-nav** [nimsandu/spicetify-bloom#284]
### Did you read the README?

- [ ] I have read the README, the theme is installed/configured correctly and the "Troubleshooting" section contains no information related to my problem

### Do you have the latest versions of Spicetify, Spotify and Bloom?

- [ ] I'm using the latest versions of Spicetify, Spotify and Bloom

### Is there already an issue for your problem?

- [ ] I have checked older issues, open and closed

### Is your problem definitely caused by the theme?

- [X] I have checked the app behavior without the theme and it is different
- [ ] I have problem with a theme custom feature

### Environment & Computer Info

```Markdown
- Spotify version: 1.2.13.661.ga588f749
- Installed from: Spotify site
- Spicetify version: 2.20.1
- Color scheme: dark
- Extensions: many
- Custom apps: none
- Bloom installation method: Spicetify Marketplace/ Powershell script (both)
```

### Description

Weird line at the top, shown in the screenshot.

### Screenshots

![ss](https://github.com/nimsandu/spicetify-bloom/assets/137557884/85eafe4a-53da-4d6a-81d4-0524d67eddbb)

**Comment by OrionsStarr** [comment]
I'm having the same issue

**Comment by murakami-marco** [comment]
I have the same issue but only installed with marketplace. Seems to be as expected if installed manually

**Comment by SunsetTechuila** [comment]
> Bloom installation method: Spicetify Marketplace/ Powershell script (both)

Both at the same time? Or tried both?

**Comment by SunsetTechuila** [comment]
Also show the full screenshot please

**Comment by matej-nav** [comment]
> 

Tried both

**Comment by matej-nav** [comment]
> > Bloom installation method: Spicetify Marketplace/ Powershell script (both)
> 
> Both at the same time? Or tried both?

I tried both, right now have it installed with the powershell script.

**Comment by matej-nav** [comment]
> Also show the full screenshot please

![ss2](https://github.com/nimsandu/spicetify-bloom/assets/137557884/894ca3e7-2000-491f-b939-9bfa68baaa3b)

**Comment by matej-nav** [comment]
> I have the same issue but only installed with marketplace. Seems to be as expected if installed manually



> I'm having the same issue


I'll reply to you again when the issue is fixed if you want

**Comment by SunsetTechuila** [comment]
1. https://github.com/nimsandu/spicetify-bloom#there-isnt-any-blur-at-all
2. https://github.com/nimsandu/spicetify-bloom#theme-doesnt-work-correctly-with-spotify-less-than-1214
duplicate of #280

**Comment by SunsetTechuila** [comment]
> I'm using the latest versions of Spicetify, Spotify and Bloom

no

> I have checked older issues, open and closed

no

> I have read the README, the theme is installed/configured correctly and the "Troubleshooting" section contains no information related to my problem

no
