### ISSUE TITLE
Lyrics are too low in lyrics-plus

### ISSUE THREAD

**Issue by Lseoksee** [nimsandu/spicetify-bloom#285]
### Did you read the README?

- [X] I have read the README, the theme is installed/configured correctly and the "Troubleshooting" section contains no information related to my problem

### Do you have the latest versions of Spicetify, Spotify and Bloom?

- [X] I'm using the latest versions of Spicetify, Spotify and Bloom

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Is your problem definitely caused by the theme?

- [X] I have checked the app behavior without the theme and it is different

### Environment & Computer Info

```Markdown
- Spotify version: 1.2.14
- Installed from: Spotify site
- Spicetify version: v2.20.1
- Color scheme: dark
- Extensions: popupLyrics.js|fullAppDisplay.js|theme.js
- Custom apps: lyrics-plus|new-releases
- Bloom installation method: Manual
```

### Description

1. Enable lyrics-plus

### Screenshots

![Screenshot 2023-06-26 15-50-59](https://github.com/nimsandu/spicetify-bloom/assets/91320047/cec8f613-5f2b-4b59-b4af-0d1bef329ee0)

The center of the lyrics-plus window is too low to display text providing lyrics and conversions buttons.

![Screenshot 2023-06-26 15-45-00](https://github.com/nimsandu/spicetify-bloom/assets/91320047/8789cffa-7bad-44bb-9faa-3a955f4f12d3)

Spotify default theme 
The lyrics are displayed completely in the center and the bottom tab menu is displayed normally.

**Comment by SunsetTechuila** [comment]
>  I have checked the app behavior without the theme and it is different
 I have problem with a theme custom feature
 
 > Installed from: (Windows Store, Spotify site, Flatpak, etc)
 
 Please fill out the information carefully. All of these fields and checkboxes are not for entertainment

**Comment by Lseoksee** [comment]
> Please fill out the information carefully. All of these fields and checkboxes are not for entertainment. They are necessary for issue reproduction.

modified it

**Comment by SunsetTechuila** [comment]
@Lseoksee @9hax hello!
can you test with this css please?
https://gist.github.com/SunsetTechuila/dccbbb919e9a61de567769e1fc6b9be3

**Comment by Lseoksee** [comment]
@SunsetTechuila 
Updated to Spotify 1.2.20 version, theme not working fully

![Desktop Screenshot 2023 09 20 - 13 57 05 44](https://github.com/nimsandu/spicetify-bloom/assets/91320047/d66b691a-d299-4dc7-bed2-1ca920851d8f)

**Comment by Lseoksee** [comment]
@SunsetTechuila 
It looks like this to me

![Screenshot 2023-09-20 14-22-09](https://github.com/nimsandu/spicetify-bloom/assets/91320047/71451bd5-bf4e-4eeb-a8cf-dd54591be95f)

**Comment by SunsetTechuila** [comment]
are you sure the theme is installed locally only?
if yes - use this script https://github.com/SunsetTechuila/spicetify-bloom/blob/dist/theme.js

**Comment by Lseoksee** [comment]
@SunsetTechuila
Is it normal to work normally this time, but not displaying album art in the background normal?

![Screenshot 2023-09-20 17-05-03](https://github.com/nimsandu/spicetify-bloom/assets/91320047/58d9ece3-a689-4bcd-8d1d-a078322c267f)

**Comment by SunsetTechuila** [comment]
> not displaying album art in the background normal

Yes, open Spotify settings and scroll to the bottom

But I recommend returning to the stable version from Spicetify Marketplace

**Comment by SunsetTechuila** [comment]
Thanks for testing
