### ISSUE TITLE
Podcast video window gets cut off as well as some of its icons

### ISSUE THREAD

**Issue by rpgdev** [nimsandu/spicetify-bloom#288]
### Did you read the README?

- [X] I have read the README, the theme is installed/configured correctly and the "Troubleshooting" section contains no information related to my problem

### Do you have the latest versions of Spicetify, Spotify and Bloom?

- [X] I'm using the latest versions of Spicetify, Spotify and Bloom

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Is your problem definitely caused by the theme?

- [X] I have checked the app behavior without the theme and it is different

### Environment & Computer Info

```Markdown
- Spotify version: 1.2.11.916.geb595a67
- Installed from: Flatpak
- Spicetify version: 2.20.3
- Color scheme: 1
- Extensions:
- Custom apps: 
- Bloom installation method: Spicetify Marketplace
```

### Description

The podcast video window gets cutoff as well as some of its icons. This happens in multiple views both default/minimized viewpoert and cinema mode.

Steps to reproduce:

1. install theme
2. play a podcast episode.

### Screenshots

![image](https://github.com/nimsandu/spicetify-bloom/assets/20094474/6df48c1c-b434-4ddd-b900-9804aa147762)

![image](https://github.com/nimsandu/spicetify-bloom/assets/20094474/ff98e2e4-cf72-4cd3-84e4-d13dd13aedfe)

![image](https://github.com/nimsandu/spicetify-bloom/assets/20094474/320d066a-ef7c-48f6-b3e6-daed49eae955)

**Comment by SunsetTechuila** [comment]
Spotify has video podcasts? 0_o

**Comment by rpgdev** [comment]
> Spotify has video podcasts? 0_o

lmao
