### ISSUE TITLE
Ability to fix "now playing" widget to the bottom without overlay

### ISSUE THREAD

**Issue by rpgdev** [nimsandu/spicetify-bloom#289]
### Provide a description of the new feature

I think it'd be awesome to have the ability to fix this widget to the bottom without overlay (this same widget, not the classic/default one). I think it would solve a lot of issues with the current theme where it simply cuts off parts of the UI when videos are involved.

**Comment by SunsetTechuila** [comment]
I'm not quite sure what you mean. Describe more detailed and clear your proposal and its implementation method

**Comment by rpgdev** [comment]
@SunsetTechuila for one it would help with https://github.com/nimsandu/spicetify-bloom/issues/288
