### ISSUE TITLE
Full Screen Mode make screen white

### ISSUE THREAD

**Issue by l29** [nimsandu/spicetify-bloom#29]
If you go into the Full Screen mode the background image get more white.
![image](https://user-images.githubusercontent.com/83277314/174188422-e72ae69f-a5ed-4985-9112-1ea313d5bac2.png)

**Comment by nimsandu** [comment]
Are you using a plug-in from marketplace?

**Comment by nimsandu** [comment]
Bug fixed by @kyrie25
