### ISSUE TITLE
Add Colors from Williamchka's fluent theme pls.

### ISSUE THREAD

**Issue by HelloTech2** [nimsandu/spicetify-bloom#292]
### Provide a description of the new feature

[https://github.com/williamckha/spicetify-fluent](url)
The colors of the Dark Variant of Fluent.

### Additional Information

![image](https://github.com/nimsandu/spicetify-bloom/assets/96501474/352c6666-50d8-459d-a0df-af3fa4129f60)

**Comment by SunsetTechuila** [comment]
will be
