### ISSUE TITLE
Tiny weird scrollbar

### ISSUE THREAD

**Issue by 42Willow** [nimsandu/spicetify-bloom#293]
![image](https://github.com/nimsandu/spicetify-bloom/assets/70784752/3942ee33-93a4-4303-9ed5-de80bc36c51f)

### Did you read the README?

- [X] I have read the README, the theme is installed/configured correctly and the "Troubleshooting" section contains no information related to my problem

### Do you have the latest versions of Spicetify, Spotify and Bloom?

- [X] I'm using the latest versions of Spicetify, Spotify and Bloom

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Is your problem definitely caused by the theme?

- [X] I have checked the app behavior without the theme and it is different

### Environment & Computer Info

```Markdown
- Spotify version: Latest stable
- Installed from: Spotify site
- Spicetify version: Latest stable
- Color scheme: Comfy
- Extensions: Adblock, etc.
- Custom apps: None
- Bloom installation method: PowerShell script
```

### Description

1. Go to a playlist
2. Scroll down
3. There's a small scrollbar which doesn't move in the top right upon hovering over the playlist section/div

### Screenshots

![image](https://github.com/nimsandu/spicetify-bloom/assets/70784752/ca6d4ee8-e3a9-49ae-a72a-64a53aa0f823)
![image](https://github.com/nimsandu/spicetify-bloom/assets/70784752/a822c8fb-542e-410e-95c6-a68f3a1e2386)
![image](https://github.com/nimsandu/spicetify-bloom/assets/70784752/52e27de9-e4f1-435d-bece-511c58a7b06d)

**Comment by SunsetTechuila** [comment]
can't reproduce
please provide Spicetify/Spotify versions and send link to playlist

**Comment by 42Willow** [comment]
```
Spotify for Windows (64 bit)
1.2.16.947.gcfbaa410
Spicetify v2.21.0
Theme: Bloom / comfy
Extensions: popupLyrics.js, fullScreenWrapper.js, copytoclipboard2.js, adblock.js, playOnYouTube.js, imageOpener.js, spotifyBackup.js, spotifyGenres.js, sortByPlayCount.js
Custom apps: marketplace, lyrics-plus, new-releases
```

Any playlist/artist page

**Comment by NEVARLeVrai** [comment]
![image](https://github.com/nimsandu/spicetify-bloom/assets/63956787/a9e17f45-aecf-441d-b3bd-ab6c073eaa2d)

**Comment by Yasssiiin** [comment]
![image](https://github.com/nimsandu/spicetify-bloom/assets/79786546/fd5741d2-652b-4c12-96c1-0a8ab8afdd84)
Same issue for me

**Comment by SunsetTechuila** [comment]
@Yasssiiin @NEVARLeVrai @42Willow hello!
can you test with these files please?
https://github.com/SunsetTechuila/spicetify-bloom/tree/dist

**Comment by SunsetTechuila** [comment]
This happens only if you use "Modern ScrollBar" snippet. Do not use it with Bloom, Bloom has its own scrollbar style
