### ISSUE TITLE
Connecting to device text is white (hard to read) and does not fit container

### ISSUE THREAD

**Issue by jahirfiquitiva** [nimsandu/spicetify-bloom#295]
### Did you read the README?

- [X] I have read the README, the theme is installed/configured correctly and the "Troubleshooting" section contains no information related to my problem

### Do you have the latest versions of Spicetify, Spotify and Bloom?

- [X] I'm using the latest versions of Spicetify, Spotify and Bloom

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Is your problem definitely caused by the theme?

- [X] I have checked the app behavior without the theme and it is different

### Environment & Computer Info

```Markdown
- Spotify version: 1.2.16.947.gcfbaa410
- Installed from: Spotify site
- Spicetify version:v2.22.1
- Color scheme: dark
- Extensions: popupLyrics.js, shuffle+.js
- Custom apps: lyrics-plus
- Bloom installation method: Manual
```

### Description

Connect to another device
While connecting, the text appears

### Screenshots

![Shot 2023-07-27 at 12 22 05@2x](https://github.com/nimsandu/spicetify-bloom/assets/10360816/008e5f63-b4dc-4603-94e9-cc8eac562799)

**Comment by SunsetTechuila** [comment]
how to get "connecting" message?

**Comment by SunsetTechuila** [comment]
reproduced

**Comment by jahirfiquitiva** [comment]
@windowz414 honest question, how do you test a desktop app on a phone? 🤔 running an emulator or something?

@SunsetTechuila thanks. I tested it on the MacBook Pro 14" screen and also a 4K display, and the issue is there in both cases

**Comment by jahirfiquitiva** [comment]
@windowz414 oh, that makes sense ... maybe it only happens with devices with a long name ... maybe you could set the text to ellipsize and be just 1 line?

anyway, the text still will be white which is hard to read with that green background

**Comment by SunsetTechuila** [comment]
I actually fixed it before, probably classname has changed
