### ISSUE TITLE
Shuffle Button icon Gone!

### ISSUE THREAD

**Issue by Yasssiiin** [nimsandu/spicetify-bloom#297]
### Did you read the README?

- [X] I have read the README, the theme is installed/configured correctly and the "Troubleshooting" section contains no information related to my problem

### Do you have the latest versions of Spicetify, Spotify and Bloom?

- [X] I'm using the latest versions of Spicetify, Spotify and Bloom

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Is your problem definitely caused by the theme?

- [X] I have checked the app behavior without the theme and it is different

### Environment & Computer Info

```Markdown
- Installed from:  Spotify site
- Bloom installation method: PowerShell script
- Spotify for Windows (64 bit) ( 1.2.17.834.g26ee1129 )
- Spicetify v2.22.2
- Theme: Bloom / dark
- Extensions: Vibrant.min.js, volumePercentageWrapper.js, imageOpener.js, spotifyGenres.js
- Custom apps: marketplace
```

### Shuffle button icon gone even after reinstalling theme for some reason same issue with smart shuffle 
![image](https://github.com/nimsandu/spicetify-bloom/assets/79786546/f2f10ff3-5a09-4bc7-8333-e8cf96a7de5e)

1.  Turn on smart shuffle from experimental 
2.  enable it on a play list 
3.  play a song recommended by spotify so it can change the icon to smart shuffle 
4.  they disappear

![image](https://github.com/nimsandu/spicetify-bloom/assets/79786546/f7a48c38-5ebe-48ee-ba89-c5a000137b18)

**Note : Disabling Smart Shuffle Brings back the icon** 
![image](https://github.com/nimsandu/spicetify-bloom/assets/79786546/458fc727-910e-4570-947b-259164c3d839)

![image](https://github.com/nimsandu/spicetify-bloom/assets/79786546/51bb13dd-1ce5-45bf-8cdc-6705c535e444)

**I don't think the theme has an icon for smart shuffle and that's why it disappears** 

**it also gives this white blank alert when enabling and disabling smart shuffle** 

> Enabled : 

![image](https://github.com/nimsandu/spicetify-bloom/assets/79786546/5cbfa071-76e5-401b-80db-2b7567708fcd)

> Disabled : 

![image](https://github.com/nimsandu/spicetify-bloom/assets/79786546/37f6bc53-af03-454c-a1c5-50440f4e6bda)

**_Can you provide a fix for this in a patch thank you!_**

> also the #293 issue in present in my theme i don't think it has anything to do with any experimental features i have tho 

![image](https://github.com/nimsandu/spicetify-bloom/assets/79786546/08cfffb8-cf44-4b68-b6d6-1e00cddc974b)

### Screenshots

Screenshot listed above ^

**Comment by prediscover** [comment]
I can reproduce this issue. And turning off smart shuffle brings shuffle icon back.

**Comment by SunsetTechuila** [comment]
fixed in the rework branch, please wait for update

**Comment by lbr-dev** [comment]
I am having the same issue. Also as you can see on the pictures more icons are missing and also "<-" icon is slightly misplaced. What could be causing this problem?
<img width="210" alt="Screenshot 2023-10-23 at 21 54 57" src="https://github.com/nimsandu/spicetify-bloom/assets/49651393/5c4c7bd9-0e11-47de-a8b2-7759c16aaddb">
<img width="1415" alt="Screenshot 2023-10-23 at 09 06 52" src="https://github.com/nimsandu/spicetify-bloom/assets/49651393/941f7272-90c9-4148-a102-810bedebe941">

**Comment by jahirfiquitiva** [comment]
Also shown in the screenshots of this issue: The `previous song` button icon is not vertically aligned with the other icons
