### ISSUE TITLE
Centering the lyrics

### ISSUE THREAD

**Issue by DivyanshKG** [nimsandu/spicetify-bloom#299]
### Provide a description of the new feature

Is it possible to make lyrics appear in the centre, i.e. with some padding on the left. 
currently this is how the lyrics appear when the library is expanded
![image](https://github.com/nimsandu/spicetify-bloom/assets/86947567/c3674fd0-f06c-4a5b-90d0-ed23f5d51510)

**Comment by SunsetTechuila** [comment]
spotify issue, install 1.2.20
