### ISSUE TITLE
song name problems

### ISSUE THREAD

**Issue by Khotyz** [nimsandu/spicetify-bloom#3]
hello, I really liked your theme, but when installing it, the name of the song is outside of where it should be, how can I correct it? I have already inserted the patch line in the config and nothing has changed, including the version I installed from the market the skip and play buttons did not appear, the command line worked normally but with this bug :/, thank you in advance ^^

Pic:
![image](https://user-images.githubusercontent.com/74627161/164844600-bd5599bf-8267-4c4b-bb1b-6faf41e243fb.png)

**Comment by nimsandu** [comment]
I'm sorry to hear that sir 
you might install the theme using marketplace
plz reset the marketplace by clicking settings icon on marketplace>scroll all the way down and click [reset marketplace]
And run following command
### Windows (PowerShell)

```powershell
Invoke-WebRequest -UseBasicParsing "https://raw.githubusercontent.com/nimsandu/spicetify-bloom/main/install.ps1" | Invoke-Expression
```

this must fix that

**Comment by Khotyz** [comment]
hello, thanks for the answer, it solved my problem, but two others appeared, the first is that the bottom bar where the player is is rising whenever I scroll down in spotify, and the second is that a kind of stain appears on the side where is the name of the song, if there's no way to solve it, I'd appreciate it anyway since my problem with the name of the songs was solved ^^

Pic:
![image](https://user-images.githubusercontent.com/74627161/164998418-b3e2f569-b00b-442d-80a5-340593123a62.png)

Gif:
![Spotify_bJ9woLDmjZ](https://user-images.githubusercontent.com/74627161/164998342-95fb51db-8c1a-44de-b268-ec8ad1718773.gif)

**Comment by nimsandu** [comment]
Its a bug sir apologize me
Ill try fixing that asap

The scrolling problem occurred due to th blurred now player

After fixing those issues ill let you know

**Comment by nimsandu** [comment]
All this questions appeared on your device cuz your huge monitor 

And I created this using my 13 inch display 

Plz apologize me

**Comment by Khotyz** [comment]
Ok, I'll wait then, thanks for helping me with the first problem and thanks for the beautiful theme ^^

**Comment by nimsandu** [comment]
Thanx for your patience sir
Ill let you know when bug fixed

**Comment by tonytkachenko** [comment]
Hey
Thanks for this cool theme! I really love it ❤️ 

Please pay attention to the broken menu view :)
![Image 001](https://user-images.githubusercontent.com/103267335/165393105-4b9ac621-981e-41fa-a0ad-91ae986c7b2f.png)

**Comment by nigelonius** [comment]
> Hey Thanks for this cool theme! I really love it ❤️
> 
> Please pay attention to the broken menu view :) ![Image 001](https://user-images.githubusercontent.com/103267335/165393105-4b9ac621-981e-41fa-a0ad-91ae986c7b2f.png)

OMG Fluent theme is doing the same thing since ver 1.1.83, I actually wanted to download bloom as an alternative but looks like the issue carried over to this theme too. Which is a shame because I have tried every theme and aesthetically, Fluent & Bloom are the best. I hope they fix this soon. Also, is there a white version of Bloom ,like there is in Fluent?

**Comment by nimsandu** [comment]
There is a light theme
But dark one is slightly better 
This bloom theme is developed associated with @williamckha who developed fluent theme
And both themes are the same JavaScript base thats why those issues occur in both themes. We both will work together to resolve all issues

**Comment by PINPAL** [comment]
> Hey Thanks for this cool theme! I really love it ❤️
> 
> Please pay attention to the broken menu view :) ![Image 001](https://user-images.githubusercontent.com/103267335/165393105-4b9ac621-981e-41fa-a0ad-91ae986c7b2f.png)

Also experiencing the same thing on the latest version of Spotify. 

**Noteable Issues on Latest Update**
 - Playlists are also not showing their cover art and instead display their name on the sidebar (see screenshot)
 - There is extra padding on the body and this creates scrollbars that allow you to scroll too far to the left or too far down forcing content off the screen
 - Numerous "fade out" effects that involve using a gradient to fade out edges of content are the incorrect color (see screenshot)
![image](https://user-images.githubusercontent.com/18197217/167697739-de173ee4-bd3c-4895-b3dd-331b47976a28.png)

**Comment by PINPAL** [comment]
Update on this, I have created a pull request to fix all the above issues

[Link to Pull #4](https://github.com/nimsandu/spicetify-bloom/pull/4)

**Comment by nimsandu** [comment]
thanx sir
