### ISSUE TITLE
Wierd line in the top of the UI

### ISSUE THREAD

**Issue by Zuntie** [nimsandu/spicetify-bloom#300]
### Did you read the README?

- [X] I have read the README, the theme is installed/configured correctly and the "Troubleshooting" section contains no information related to my problem

### Do you have the latest versions of Spicetify, Spotify and Bloom?

- [X] I'm using the latest versions of Spicetify, Spotify and Bloom

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Is your problem definitely caused by the theme?

- [X] I have checked the app behavior without the theme and it is different

### Environment & Computer Info

```Markdown
- Spotify version: 1.2.21.1104.g42cf0a50
- Installed from: (Windows Store, Spotify site, Flatpak, etc) Spotify Site
- Spicetify version: 2.24.2
- Color scheme: Dark but is irrelevant.
- Extensions: adblock.js
- Custom apps: None
- Bloom installation method: (Spicetify Marketplace/PowerShell script/Bash script/Manual) Spicetify Marketplace, also tried PowerShell script.
```

### Description

There were other closed issue on this topic, but none of the solutions worked.

I tried the configurations that was recommended in the troubleshooting guide, but didn't work.
I tried the solution in #280 unfortunately didn't work either.

I'm sorry if i missed something in other closed issues or in the troubleshooting guide.

### Screenshots

![image](https://github.com/nimsandu/spicetify-bloom/assets/60542183/394bd7e9-fafe-4498-ac89-0948cd63178a)
![image](https://github.com/nimsandu/spicetify-bloom/assets/60542183/010f4958-687e-4925-9be0-e414b1d47932)

**Comment by SunsetTechuila** [comment]
![image](https://github.com/nimsandu/spicetify-bloom/assets/115353812/f464562d-76d0-40b2-a8c2-db5d60e11b49)
show me this window

**Comment by Zuntie** [comment]
![image](https://github.com/nimsandu/spicetify-bloom/assets/60542183/aef1345b-8438-42a9-bf1a-e6869e646a23)
There you go.

**Comment by SunsetTechuila** [comment]
and you have already done [this](https://github.com/nimsandu/spicetify-bloom/issues/280#issuecomment-1616436931), right?

**Comment by Zuntie** [comment]
Yes. I ran the command `spicetify backup apply`
![image](https://github.com/nimsandu/spicetify-bloom/assets/60542183/e54b5bff-6342-472a-9077-87ea0260d08f)

Then ran the command `spicetify restore backup`
![image](https://github.com/nimsandu/spicetify-bloom/assets/60542183/73ce3bcf-250e-4503-ab93-c6b85b9f522f)

I used `spicetify apply` as instructed in the previous image.
![image](https://github.com/nimsandu/spicetify-bloom/assets/60542183/21eee559-765a-48a6-bc2e-8e0552fb10df)


I'm not sure i did it correctly.

**Comment by SunsetTechuila** [comment]
![image](https://github.com/nimsandu/spicetify-bloom/assets/115353812/bc53d573-ad97-4328-ab0a-2fa4c3adbed9)
wrong!

**Comment by Zuntie** [comment]
Ahh, my bad. I don't understand "install the newest spotify over the current one".
Install the newest version of Spotify from their website, in the same folder as the current installed one?

**Comment by SunsetTechuila** [comment]
yes
