### ISSUE TITLE
Unable to resize library pane

### ISSUE THREAD

**Issue by 10an** [nimsandu/spicetify-bloom#301]
### Did you read the README?

- [X] I have read the README, the theme is installed/configured correctly and the "Troubleshooting" section contains no information related to my problem

### Do you have the latest versions of Spicetify, Spotify and Bloom?

- [X] I'm using the latest versions of Spicetify, Spotify and Bloom

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Is your problem definitely caused by the theme?

- [X] I have checked the app behavior without the theme and it is different

### Environment & Computer Info

```Markdown
- Spotify version:
Spotify for Windows (64 bit)
1.2.22.982.g794acc0a
Spicetify v2.24.2
Theme: Bloom / dark
Extensions: beautiful-lyrics.js, spotifyGenres.js, theme.js
Custom apps: marketplace

- Installed from: (Windows Store, Spotify site, Flatpak, etc)
Winget

- Spicetify version:
v2.24.2

- Color scheme:
Dark

- Extensions:
Beautiful Lyrics
Spotify Genres
Pointers
Smooth Progress
Hide Friends Activity Button
Smooth Reveal Playlist Gradient
Left Aligned Heart Icons

- Bloom installation method: (Spicetify Marketplace/PowerShell script/Bash script/Manual)
Marketplace
```

### Description

1. Install theme from marketplace
Done.

Should be able to resize when hovering between the library pane and center pane. 
Disabling the theme resolves this.

### Screenshots

![Spotify_XniAqHnnfV](https://github.com/nimsandu/spicetify-bloom/assets/81302994/d915cc66-88c6-4387-94c8-6c1729af23a0)

![Spotify_yCa28fQde8](https://github.com/nimsandu/spicetify-bloom/assets/81302994/8baf481b-ec98-4989-b720-cf66806e319e)

**Comment by SunsetTechuila** [comment]
known issue, please wait for update
