### ISSUE TITLE
Back Button Messed Up & Blur Only Working on some Items

### ISSUE THREAD

**Issue by K3NOXOFFICIAL** [nimsandu/spicetify-bloom#302]
### Did you read the README?

- [X] I have read the README, the theme is installed/configured correctly and the "Troubleshooting" section contains no information related to my problem

### Do you have the latest versions of Spicetify, Spotify and Bloom?

- [X] I'm using the latest versions of Spicetify, Spotify and Bloom

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Is your problem definitely caused by the theme?

- [X] I have checked the app behavior without the theme and it is different

### Environment & Computer Info

```Markdown
- Spotify version: 1.2.22.982
- Installed from: Spotify Site
- Spicetify version: V2.24.2
- Color scheme: darkmono
- Extensions:
- Custom apps: lyrics plus, new releases, reddit
- Bloom installation method: PowerShell Bash Manual
```

### Description

Back Button For Folders is The library symbol instead of the back arrow as well as that Blur Only seems to work on the Top Bar and the Clickable Menus and isn't working on now playing or other cards.

### Screenshots

Back Button For Folders is The library symbol instead of the back arrow.

![Screenshot 2023-10-14 170230](https://github.com/nimsandu/spicetify-bloom/assets/46091052/48ab1ff8-2350-4548-b6ea-d40f174e0781)

<br /> <br /> <br />

Blur Only seems to work on Top Bar and the Clickable Menus,
Not working on now playing or other cards.

![Screenshot 2023-10-14 171319](https://github.com/nimsandu/spicetify-bloom/assets/46091052/e67c3d4f-5bbf-412d-9c88-5ca2973c0976)

**Comment by SunsetTechuila** [comment]
> Back Button For Folders is The library symbol instead of the back arrow.

Known issue, please wait for update

> Blur not working on now playing

Ambient extension issue

**Comment by EliasOS** [comment]
**I have the same problem with the button to return to the library:**
![bug_with_icon](https://github.com/nimsandu/spicetify-bloom/assets/61661800/80094b75-9100-4f4f-ae51-e435c014a5bd)

And not only that, if I go into a **subfolder** the icon does not change to that of the subfolder as @SunsetTechuila said, but _is still the one for the books_. Here I go into the Anime folder that I have in the folder you see previously:![image](https://github.com/nimsandu/spicetify-bloom/assets/61661800/450be86a-e776-485c-96eb-b7f38a7213f3)

**Comment by nimsandu** [comment]
libraryX enhancements fixed these issues with various commits! please reopen if these issues still presents! 
keep blooming!
