### ISSUE TITLE
Friend activity, profile, navigation button(s) misplaced / horizontal line bugged

### ISSUE THREAD

**Issue by Yoshlix** [nimsandu/spicetify-bloom#304]
### Did you read the README?

- [X] I have read the README, the theme is installed/configured correctly and the "Troubleshooting" section contains no information related to my problem

### Do you have the latest versions of Spicetify, Spotify and Bloom?

- [X] I'm using the latest versions of Spicetify, Spotify and Bloom

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Is your problem definitely caused by the theme?

- [X] I have checked the app behavior without the theme and it is different

### Environment & Computer Info

```Markdown
- Spotify version: 1.2.23.1125.g920a7ada
- Installed from: Spotify site
- Spicetify version: 2.27.0
- Color scheme: comfy
- Extensions: /
- Custom apps: /
- Bloom installation method: Manual
```

### Description

The back/forward buttons, profile button and friend activity button are misplaced. There is also a strange horizontal line.

### Screenshots

![grafik](https://github.com/nimsandu/spicetify-bloom/assets/75274054/cbd720c2-1b59-4dd2-ab3a-9ebf80f1aed5)

**Comment by EliasOS** [comment]
![image](https://github.com/nimsandu/spicetify-bloom/assets/61661800/8c1a4653-8926-4a01-b77d-7bf3927e15f0)
I have the same problem after updating Spotify, they must have changed something in the interface
