### ISSUE TITLE
Play/Pause Button on Playlist Top

### ISSUE THREAD

**Issue by l29** [nimsandu/spicetify-bloom#31]
If you on Top of the Playlist Page:
![image](https://user-images.githubusercontent.com/83277314/174607830-82e71001-0c68-4358-85e6-ebac4b0dead7.png)

If you scroll down:
![image](https://user-images.githubusercontent.com/83277314/174607869-07604eda-3ba3-4fd8-9300-650cd071f821.png)

**Comment by nimsandu** [comment]
you are talking about the difference right?

**Comment by nimsandu** [comment]
if you are which color would you prefer?
@v6r

**Comment by nimsandu** [comment]
Above play button is a feature by Spotify @v6r so we let it to be
