### ISSUE TITLE
cant see if random music button is enabled

### ISSUE THREAD

**Issue by kimskaj** [nimsandu/spicetify-bloom#322]
### Did you read the README?

- [X] I have read the README, the theme is installed/configured correctly and the "Troubleshooting" section contains no information related to my problem

### Do you have the latest versions of Spicetify, Spotify and Bloom?

- [X] I'm using the latest versions of Spicetify, Spotify and Bloom

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Is your problem definitely caused by the theme?

- [X] I have checked the app behavior without the theme and it is different

### Environment & Computer Info

```Markdown
- Spotify version: newst avaible with spicetiy
- Installed from: (Spotify site, )
- Spicetify version: newest
- Color scheme:
- Extensions:
- Custom apps:
- Bloom installation method: (Spicetify Marketplace)
```

### Description

cant see if random music button is enabled when its clicked

### Screenshots

![gs](https://github.com/nimsandu/spicetify-bloom/assets/155857142/aee75723-3dee-41b4-8de1-add6a2ae6ce1)

**Comment by nimsandu** [comment]
fixed by @sanoojes ! Thanks!!
