### ISSUE TITLE
Sidebar colors

### ISSUE THREAD

**Issue by AndresF2016** [nimsandu/spicetify-bloom#324]
### Provide a description of the new feature

The current version of Bloom theme doesn't exactly change the sidebar colors and keeps the standar color scheme rules(?), which means the sidebar buttons have a background that follows the "main" color scheme and not leaving the whole sidebar color solid like the old "Fluent" theme...
_So i expect the sidebar doesn't have the "main"  color on his buttons backrounds and follows the "sidebar" color, just like the old "Fluent" theme._

**Current --> What i expect:**
![example - bloom sidebar 1](https://github.com/nimsandu/spicetify-bloom/assets/112676001/0bd14c3e-c4d4-40a0-8978-98a4119bd515)

_Specifications:_
Spotify v1.2.26.1187
Spicetify v2.29.1

**Comment by SunsetTechuila** [comment]
will be changed only in fluent-dark and fluent-light color schemes

screenshots are old and wip

![image](https://github.com/nimsandu/spicetify-bloom/assets/115353812/c29f825f-6539-4c29-af77-6089a0c4dc56)

![image](https://github.com/nimsandu/spicetify-bloom/assets/115353812/6cab13d8-396b-4b63-a989-10075de8e118)

**Comment by AndresF2016** [comment]
> will be changed only in fluent-dark and fluent-light color schemes
> 
> screenshots are old and wip
> 
> ![image](https://private-user-images.githubusercontent.com/115353812/294841149-c29f825f-6539-4c29-af77-6089a0c4dc56.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwMzYzMzUsIm5iZiI6MTcwNTAzNjAzNSwicGF0aCI6Ii8xMTUzNTM4MTIvMjk0ODQxMTQ5LWMyOWY4MjVmLTY1MzktNGMyOS1hZjc3LTYwODlhMGM0ZGM1Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExMlQwNTA3MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mM2RjMGJhMmJhMTFlYjA2ZDNlYmFhMTFiNmFlOWQxMGRjMzRkMGZkMGMwZGUxY2MxNjM5YjUyNzhjZTIyNGMzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.U4nGCOzPHCjxO1aBPO_ErokpvliJN5zHsHzLvPQtS74)
> 
> ![image](https://private-user-images.githubusercontent.com/115353812/294841164-6cab13d8-396b-4b63-a989-10075de8e118.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwMzYzMzUsIm5iZiI6MTcwNTAzNjAzNSwicGF0aCI6Ii8xMTUzNTM4MTIvMjk0ODQxMTY0LTZjYWIxM2Q4LTM5NmItNGI2My1hOTg5LTEwMDc1ZGU4ZTExOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExMlQwNTA3MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNWNiNjQ5NTA4MDM1Yjg0Mzg5NDQyNGNhZjNlZDU4YTQ3OTZmM2UwOTQ3Mzk3MTRlOTliYTZjZTk0YTY2NGEzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Sxw4QIUSaBcx6l7oQ7wYlZ1yH3wWpJUN1YbcrKr51sE)


I see... So there's gonna be new color schemes like **fluent-dark** and **fluent-light**?
So, those screenshots are a WIP from a future "Bloom" update or something? Also... That "Mica" effect is just a wallpaper inside spotify app? Or did you used a version of Spotify where is compatible with MicaForEveryone? I ask because i'm curious those buttons of **minimize, maximize** and **close** buttons aren't black as normally is... Like this one:
![Captura de pantalla 2024-01-11 234633](https://github.com/nimsandu/spicetify-bloom/assets/112676001/2b171e0f-9492-4ef3-9018-86ef34e97c4e)

**Comment by nimsandu** [comment]
@AndresF2016 yes! we were developing a way to simulate the mica feeling for our users! it didn't go quite well, as you know spotify is a chromium-based web-app. using this type of simulations might cause increases in recourse usage from our users' pcs. 
We lost between the decision whether to make it beautiful or to protect the principle called Calm and Cleen! so like always, we had to surrender in front of fluent2 principles
