### ISSUE TITLE
Search Bar Looses Focus While Typing

### ISSUE THREAD

**Issue by LoneWolf4713** [nimsandu/spicetify-bloom#326]
### Did you read the README?

- [X] I have read the README, the theme is installed/configured correctly and the "Troubleshooting" section contains no information related to my problem

### Do you have the latest versions of Spicetify, Spotify and Bloom?

- [X] I'm using the latest versions of Spicetify, Spotify and Bloom

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Is your problem definitely caused by the theme?

- [X] I have checked the app behavior without the theme and it is different

### Environment & Computer Info

```Markdown
- Spotify version: 1.2.26.1187.g36b715a1
- Installed from: Flatpak, 
- Spicetify version: 2.30.8
- Color scheme: All
- Extensions: Full Screen By Daksh2k and Adblock
- Custom apps: No
- Bloom installation method: Spicetify Marketplace
```

### Description

Hello, love this theme, but the search bar looses focus while typing, I mean, if there's a .5 sec in typing the next character. 
In Default spotify, the search happens while you type but the search bar doesn't lose focus, while after applying Bloom it does. 
therefore I can't search and any spacebar while typing pauses the song.
I'm on wayland, or else I would've attached a screen record.

**Comment by Davoleo** [comment]
I can record footage of the issue, 
every time the bottom line/shadow disappears it means the search box loses focus which prevents me from writing my query
![Spotify_mhbr4WvGQK](https://github.com/nimsandu/spicetify-bloom/assets/24458276/0d142ea0-9bc8-40fb-81b6-8c76217fc5c4)
This is especially frustrating when you have to press space since Spotify interprets it as if you wanted to play/pause the current song.

**Comment by SunsetTechuila** [comment]
I noticed the issue, please wait

**Comment by 1stLocal** [comment]
I have same issue

**Comment by JimDude7404** [comment]
Yeah I am having the same issue, I wonder if downgrading can solve the issue.

**Comment by aurelbdx** [comment]
> Yeah I am having the same issue, I wonder if downgrading can solve the issue.

same problem with the previous version 1.2.26.1187.
I would like to downgrade Bloom but we can't :(

**Comment by aaelyxa** [comment]
i also have this problem plssss fix it. :(

**Comment by NhomNhom0** [comment]
same issue

**Comment by nimsandu** [comment]
this was fixed with latest commits, please update spotify, spicetify and bloom!
