### ISSUE TITLE
Windows border

### ISSUE THREAD

**Issue by vvipallwe** [nimsandu/spicetify-bloom#328]
### Did you read the README?

- [X] I have read the README, the theme is installed/configured correctly and the "Troubleshooting" section contains no information related to my problem

### Do you have the latest versions of Spicetify, Spotify and Bloom?

- [X] I'm using the latest versions of Spicetify, Spotify and Bloom

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Is your problem definitely caused by the theme?

- [X] I have checked the app behavior without the theme and it is different

### Environment & Computer Info

```Markdown
Spotify for Windows (64 bit)
1.2.29.605.g66a43ceb
Spicetify v2.30.0
Theme: Bloom / violet
Extensions: featureshuffle.js, adblock.js, fullScreenWrapper.js, volumePercentageWrapper.js, copy-lyrics.js, songstats.js, spotifyBackup.js, scannables.js, made-for-you-shortcut.js, romaja_lyrics.js, theme.js
Custom apps: marketplace
```

### Description

Please fix it

### Screenshots

![Screenshot (325)](https://github.com/nimsandu/spicetify-bloom/assets/81069318/51abb2f6-7966-4cb1-9971-9dcf719c271e)
look at corner (up right, minimize exit restore)

**Comment by aurelbdx** [comment]
“Hide your friends' activity” in the Marketplace may temporarily solve your problem
