### ISSUE TITLE
Media Buttons not visible

### ISSUE THREAD

**Issue by Kamo005** [nimsandu/spicetify-bloom#329]
### Did you read the README?

- [X] I have read the README, the theme is installed/configured correctly and the "Troubleshooting" section contains no information related to my problem

### Do you have the latest versions of Spicetify, Spotify and Bloom?

- [X] I'm using the latest versions of Spicetify, Spotify and Bloom

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Is your problem definitely caused by the theme?

- [X] I have checked the app behavior without the theme and it is different

### Environment & Computer Info

```Markdown
- Spotify version: v2.30.0
- Installed from: Spotify site
- Spicetify version: v2.30.0
- Color scheme: Comfy
- Extensions: fullAppDisplay.js, beautiful-lyrics.js, power-bar.js
- Custom apps: marketplace, ncs-visualizer, stats
- Bloom installation method: Spicetify Marketplace, Bash script, Manual
```

### Description

1. Media buttons are not visible. 

### Screenshots

![Screenshot Spotify-Spotify Free-18-25-13@2x](https://github.com/nimsandu/spicetify-bloom/assets/73993292/78db193f-15a9-4d0d-8e4a-dc41251fbe97)

**Comment by windowz414** [comment]
I assume this is a bug with Spicetify rather than Bloom itself, I'm gonna look into this and troubleshoot.

**Comment by Kamo005** [comment]
Okay, thanks! Please keep me updated if possible.

**Comment by stel-bl** [comment]
...I really haven't updated this issue in a while have I?

@Kamo005, sorry for my absence. I've been extremely swamped over here ever since the school started and I could get to check the issues again just now in my free time.

As for this issue, I'm pretty sure this is because of a derp at Spicetify itself so keeping Spicetify up to date should keep you up and going.
