### ISSUE TITLE
Shuffle button disappeared and buttons are not aligned either when language is Traditional Chinese

### ISSUE THREAD

**Issue by ElliotCHEN37** [nimsandu/spicetify-bloom#330]
### Did you read the README?

- [X] I have read the README, the theme is installed/configured correctly and the "Troubleshooting" section contains no information related to my problem

### Do you have the latest versions of Spicetify, Spotify and Bloom?

- [X] I'm using the latest versions of Spicetify, Spotify and Bloom

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Is your problem definitely caused by the theme?

- [X] I have checked the app behavior without the theme and it is different

### Environment & Computer Info

```Markdown
- Spotify version: 1.2.30.1135.g02fef27a
- Installed from: Spotify site
- Spicetify version: v2.31.1
- Color scheme: darkmono
- Extensions: adblock.js, allOfArtist.js, made-for-you-shortcut.js, volumePercentage.js, theme.js
- Custom apps: Spicetify market
- Bloom installation method: Spicetify Marketplace
```

### Description

![2024-02-09 12 00 53](https://github.com/nimsandu/spicetify-bloom/assets/109361374/7f111f8e-a638-4d00-a373-6203313998f5)
When I set the language to English, everything works fine. But when I set it to Traditional Chinese, the Shuffle button disappeared. Buttons are not aligned either

### Screenshots

![2024-02-09 12 00 53](https://github.com/nimsandu/spicetify-bloom/assets/109361374/7f111f8e-a638-4d00-a373-6203313998f5)

**Comment by ElliotCHEN37** [comment]
If I disable the "Smart shuffle" from the experiment setting, though the shuffle icon shows, it is un-clickable

**Comment by IdkWhatToCallMe123** [comment]
I have the same issue xd

**Comment by nimsandu** [comment]
@IdkWhatToCallMe123 @ElliotCHEN37 do we still have the issue?

**Comment by ElliotCHEN37** [comment]
after testing i found a new issue
the play button is white
![image](https://github.com/nimsandu/spicetify-bloom/assets/109361374/021e01ea-8f11-4cef-a417-ebfe65507e09)

**Comment by ElliotCHEN37** [comment]
thx for fixing them, looking forward to next update

**Comment by nimsandu** [comment]
@ElliotCHEN37 can we check the issues now?

**Comment by ElliotCHEN37** [comment]
the button is still white (re-installed via marketplace)

**Comment by nimsandu** [comment]
how about reinstalling with the script! let me knw how it went afterwards!

```powershell
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
iex "& { $(iwr -useb 'https://raw.githubusercontent.com/nimsandu/spicetify-bloom/main/install/PowerShell/Bloom.ps1') }"
```

this works ryt on mine, thats why its hard to figure out whats wrong!
![image](https://github.com/nimsandu/spicetify-bloom/assets/57834844/187b9dcb-8e0b-40bd-8a22-2138eb909457)

**Comment by ElliotCHEN37** [comment]
still not working...
![image](https://github.com/nimsandu/spicetify-bloom/assets/109361374/2546477f-5041-42f2-8d9a-4d020776da1a)

**Comment by nimsandu** [comment]
hmm. well lets see what we can do! btw whats your spicetify version?

**Comment by ElliotCHEN37** [comment]
適用 Windows (64 位元) 的 Spotify
1.2.40.599.g606b7f29
Spicetify v2.36.13
Theme:
Extensions: scannables.js, copytoclipboard.js, adblock.js
Custom apps: marketplace, lyrics-plus

**Comment by nimsandu** [comment]
Thanks!!
Will see what we can do!

**Comment by ElliotCHEN37** [comment]
solved in latest version
