### ISSUE TITLE
the icons of  the marketplace and apps are hidden 

### ISSUE THREAD

**Issue by NotJellyPig** [nimsandu/spicetify-bloom#334]
### Did you read the README?

- [X] I have read the README, the theme is installed/configured correctly and the "Troubleshooting" section contains no information related to my problem

### Do you have the latest versions of Spicetify, Spotify and Bloom?

- [X] I'm using the latest versions of Spicetify, Spotify and Bloom

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Is your problem definitely caused by the theme?

- [X] I have checked the app behavior without the theme and it is different

### Environment & Computer Info

```Markdown
- Spotify version:1.2.31
- Installed from: ( Spotify site)
- Spicetify version:2.36
- Color scheme:
- Extensions:ad blocker/keyboard shortcut
- Custom apps:name the tune
- Bloom installation method: (Spicetify Marketplace)
```

### Description

it was normal at first but today when i open spotify i notice the market place icon hidden i restart it many time but nothing happend 

### Screenshots

![Desktop Screenshot 2024 03 26 - 16 24 17 99](https://github.com/nimsandu/spicetify-bloom/assets/147732672/4faae684-6bb5-45ec-8f72-a27426d7395a)

**Comment by stel-bl** [comment]
I don't think it's really "hidden" but rather the resource failing to load. Can you try reinstalling Bloom using the instructions in the README?

**Comment by lucabosul** [comment]
I have the same issue. I tried reinstalling but it doesn't seem to work.

**Comment by NotJellyPig** [comment]
It s the same still to this moment the icon is hidden even after reinstalling and even updating spicetify

**Comment by stel-bl** [comment]
Then I'll try to inspect this myself. I'm still pretty sure that the resource is failing to load.

**Comment by stel-bl** [comment]
Well you could try to work on the code if you can bear with JS since Spicetify themes are generally just JS scripts that override the Spotify defaults IIRC.

**Comment by sanoojes** [comment]
Fixed it its alright now

**Comment by nimsandu** [comment]
@NotJellyPig , the issue was fixed by pull requests from @sanoojes & @yanus ! could you please update bloom and confirm the fix? so we can close this issue

**Comment by BLACK4585** [comment]
Fixed for me ❤️
