### ISSUE TITLE
[enhancement] icons little bit off and name of the song being covered

### ISSUE THREAD

**Issue by Neondroidd** [nimsandu/spicetify-bloom#346]
### Provide a description of the new feature

some of the icons don't match where they are, like the play button on the home is a bit slanted, and the name of the song is covered by the photo of the song, and can the color of the icons like those on the playbar and friendlist be changed so the colors don't blend in too much?

### Additional Information

If the name of the song is covered, it's new because Spotify just updated it

![image](https://github.com/nimsandu/spicetify-bloom/assets/91836929/53ac6cf8-c4b8-446f-9952-b6a0dc0a36d6)

**Comment by BedBug2479** [comment]
yep same with the v1.2.37.701.ge66eb7bc

![image](https://github.com/nimsandu/spicetify-bloom/assets/43089040/40fb526a-beec-4fdd-b5b1-2526288e13e5)

**Comment by sanoojes** [comment]
update spicetify it should solve the issue. run spicetify update and spicetify backup apply

**Comment by BedBug2479** [comment]
> update spicetify it should solve the issue. run spicetify update and spicetify backup apply

spicetify is upto date but still it is coming

**Comment by kernelb00t** [comment]
@BedBug2479 what is your spicetify version (`spicetify -v`), how did you installed the theme, which commit is the latest if you installed manually, what is your spotify version, and what is your OS and its version?

**Comment by BedBug2479** [comment]
> @BedBug2479 what is your spicetify version (`spicetify -v`), how did you installed the theme, which commit is the latest if you installed manually, what is your spotify version, and what is your OS and its version?

![image](https://github.com/nimsandu/spicetify-bloom/assets/43089040/d0d6f345-6bb5-4337-a5d9-751bb7f4f624)

Spotify v1.2.37.701.ge66eb7bc
Windows 10 Build 22H2 19045.4291
Installed through marketplace

**Comment by BedBug2479** [comment]
Hi it is working f9 now for me
it can be closed according to me
