### ISSUE TITLE
UI Bugs

### ISSUE THREAD

**Issue by Nimai-HK** [nimsandu/spicetify-bloom#347]
### Did you read the README?

- [X] I have read the README, the theme is installed/configured correctly and the "Troubleshooting" section contains no information related to my problem

### Do you have the latest versions of Spicetify, Spotify and Bloom?

- [X] I'm using the latest versions of Spicetify, Spotify and Bloom

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Is your problem definitely caused by the theme?

- [X] I have checked the app behavior without the theme and it is different

### Environment & Computer Info

```Markdown
- Spotify version: Spotify for Windows (64 bit)  1.2.37.701.ge66eb7bc
- Installed from: Spotify site
- Spicetify version: v2.36.11
- Color scheme: Dark-Mono ( applicable to all color schemes )

- Extensions: Ad Block, Volume Percentage, Scannables ( None affecting Base UI) 
             NPV Ambience (affects now playing UI Album Art Only)

- Custom apps: None
- Bloom installation method: Spicetify Marketplace/PowerShell script/Manual  (all three have same issue recurring)
```

### Description

1. The Base UI tends to hide/ mess around with the search box, and top of the titlebar on this version on spotify.

2. The text on the now playing view is darker or not visible.

3. Search keeps unfocusing, and every interval needs to be selected again.

4. Icons on the playing bar seem to have errors with rendering.

5. Home button disappears.

6. Buttons on the Playing Bar seem to be misaligned on smaller screens.

7. Back button in folders still appears with the Library icon.

8. Blur is messed up at window borders, lyrics view, and now playing view

9. Marketplace not being rendered properly, glitching into the title bar.

10. The playing bar song text seems to glitch into the album art.

11. Elements like back, forward, and other buttons on the title bar are almost non clickable on smaller displays.

This is a compilation of all the issues I have come across with the UI, with the title bar issues being worsened since the new update. Others may have already highlighted some stuff reported here. 
Thank you.

### Screenshots

![image](https://github.com/nimsandu/spicetify-bloom/assets/169251488/7037bf31-f77c-4ccc-9f9f-11216fa9e98c)
![image](https://github.com/nimsandu/spicetify-bloom/assets/169251488/8a37bfca-88e0-45ef-8f4c-370b104d5571)

The last image is of Spotify with Spicetify with no theme^

**Comment by sanoojes** [comment]
> Tried. Recurring issue in all three methods of installation [ including full reinstall (spotify, spicetify, and bloom)]

check your extensions it might be the issue

New Spotify 1.2.37.701.ge66eb7bc with no mods should look like this. 
something is modifying your spotify header 
![image](https://github.com/nimsandu/spicetify-bloom/assets/93819264/2440bf10-f224-4959-aebb-d1755b290876)

**Comment by Nimai-HK** [comment]
Nope, that's the new UI of Spotify.
other themes like comfy seem to work with it.
1.2.37.701.ge66eb7bc version looks like 
![image](https://github.com/nimsandu/spicetify-bloom/assets/169251488/25d75104-f795-40e0-82ba-709fc4550b52)
