### ISSUE TITLE
Title bar looks buggy on MacOS

### ISSUE THREAD

**Issue by AushevAhmad** [nimsandu/spicetify-bloom#349]
### Did you read the README?

- [X] I have read the README, the theme is installed/configured correctly and the "Troubleshooting" section contains no information related to my problem

### Do you have the latest versions of Spicetify, Spotify and Bloom?

- [X] I'm using the latest versions of Spicetify, Spotify and Bloom

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Is your problem definitely caused by the theme?

- [X] I have checked the app behavior without the theme and it is different

### Environment & Computer Info

```Markdown
- Spotify version: 1.2.37.701.ge66eb7bc
- Installed from: Spotify site
- Spicetify version: 2.36.11
- Color scheme: dark
- Extensions: adblock.js, noTrackingLinks.js, utilities.js, theme.js
- Custom apps: marketplace
- Bloom installation method: Spicetify Marketplace
```

### Description

1. Install Spotify (Spotify Website)
2. Install spicetify and spicetify marketplace
3. Install theme
4. Elements like back, forward, and other buttons on the title bar are almost non clickable

### Screenshots

![image](https://github.com/nimsandu/spicetify-bloom/assets/113457231/1ad74586-ef1a-4a54-a95c-d5625dd226ce)

**Comment by sanoojes** [comment]
ohh sorry i explictly set the margin and width for windows i will fix it in next pr

**Comment by juanra** [comment]
<img width="251" alt="SCR-20240716-fxpa" src="https://github.com/user-attachments/assets/099eb850-1077-4867-9f0e-3def82566c02">

Sorry guys but this issue is not fixed...
