### ISSUE TITLE
Toastify breaking playlist bar.

### ISSUE THREAD

**Issue by Bac3D** [nimsandu/spicetify-bloom#35]
When i open spotify using toastify it breaks the playlist sidebar.
https://youtu.be/78IbZg1W6bw

**Comment by nimsandu** [comment]
Oh we never tested it with tostify

**Comment by nimsandu** [comment]
Lets try something and let you know what to do

**Comment by Bac3D** [comment]
Ok

**Comment by Astromations** [comment]
> When i open spotify using toastify it breaks the playlist sidebar. https://youtu.be/78IbZg1W6bw

what spotify and spicetify version are you using in that

**Comment by Bac3D** [comment]
Latest

**Comment by Astromations** [comment]
> Latest

1.1.88 and 2.10.1?

**Comment by Bac3D** [comment]
![image](https://user-images.githubusercontent.com/91746244/175831010-dd15180d-693f-42c4-9244-3a115e4b776c.png)
![image](https://user-images.githubusercontent.com/91746244/175831018-6725a8ae-d5d2-4b1f-8844-c030dbbbcdfc.png)
I installed spotify with the installer, episodes are missing because i removed them with a snippet.

**Comment by nimsandu** [comment]
@Bac3D From where you downloaded Spotify (Spotify web or microsoft store)

**Comment by Bac3D** [comment]
I downloaded it from this link: https://www.spotify.com/it/download/windows/
@nimsandu

**Comment by nimsandu** [comment]
@Bac3D Alright 
Did you installed the theme after toastify installation

**Comment by Bac3D** [comment]
yes, I installed the theme after installing toastify

**Comment by nimsandu** [comment]
@Bac3D can you run the powershell script to update the theme and check wether issue still presents

**Comment by nimsandu** [comment]
@Bac3D ?

**Comment by nimsandu** [comment]
@Bac3D Im closing this issue because its no longer active 

But if you still have the issue don't hesitate to open another issue 

Enjoy bloom
Thanks
