### ISSUE TITLE
Marketplace not in middle

### ISSUE THREAD

**Issue by BedBug2479** [nimsandu/spicetify-bloom#354]
### Did you read the README?

- [X] I have read the README, the theme is installed/configured correctly and the "Troubleshooting" section contains no information related to my problem

### Do you have the latest versions of Spicetify, Spotify and Bloom?

- [X] I'm using the latest versions of Spicetify, Spotify and Bloom

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Is your problem definitely caused by the theme?

- [X] I have checked the app behavior without the theme and it is different

### Environment & Computer Info

```Markdown
- Spotify version: 1.2.38.720.ga4a70a0e
- Installed from: (Windows Store, Spotify site, Flatpak, etc) Spotify Site
- Spicetify version:v2.36.11
- Color scheme: Bloom Daark
- Bloom installation method: (Spicetify Marketplace/PowerShell script/Bash script/Manual) Marketplace
```

### Description

The marketplace is not in the middle after updating the marketplace

### Screenshots

![image](https://github.com/nimsandu/spicetify-bloom/assets/43089040/4a3fed14-5289-40e7-bf83-fd148ab62e14)

**Comment by sanoojes** [comment]
yess it is. @nimsandu can you check out my pr

**Comment by sanoojes** [comment]
also i made a new theme do check out [better-bloom](https://github.com/sanoojes/better-bloom)

**Comment by BedBug2479** [comment]
this bug got resolved after updating spicetify
