### ISSUE TITLE
the profile/notifcation is merged with window cotrols

### ISSUE THREAD

**Issue by BedBug2479** [nimsandu/spicetify-bloom#356]
### Did you read the README?

- [X] I have read the README, the theme is installed/configured correctly and the "Troubleshooting" section contains no information related to my problem

### Do you have the latest versions of Spicetify, Spotify and Bloom?

- [X] I'm using the latest versions of Spicetify, Spotify and Bloom

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Is your problem definitely caused by the theme?

- [X] I have checked the app behavior without the theme and it is different

### Environment & Computer Info

```Markdown
- Spotify version: 1.2.38.720.ga4a70a0e
- Installed from: (Windows Store, Spotify site, Flatpak, etc) Spotify Site
- Spicetify version:v2.36.12
- Color scheme: Bloom Dark
- Bloom installation method: (Spicetify Marketplace/PowerShell script/Bash script/Manual) Marketplace
```

### Description

After updating the spicetify and re-applying the theme the profile section and the window controls are being overlaped

### Screenshots

![image](https://github.com/nimsandu/spicetify-bloom/assets/43089040/9010c59f-c064-4c79-885b-454fa0f3263d)

**Comment by nimsandu** [comment]
this issue was patched temporally with the latest commit, can you check and confirm now?

**Comment by BedBug2479** [comment]
> this issue was patched temporally with the latest commit, can you check and confirm now?

yes this has been fixed

thnx

**Comment by nimsandu** [comment]
thanks for your issue @BedBug2479
