### ISSUE TITLE
UI bugs

### ISSUE THREAD

**Issue by kernelb00t** [nimsandu/spicetify-bloom#358]
### Did you read the README?

- [X] I have read the README, the theme is installed/configured correctly and the "Troubleshooting" section contains no information related to my problem

### Do you have the latest versions of Spicetify, Spotify and Bloom?

- [X] I'm using the latest versions of Spicetify, Spotify and Bloom

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Is your problem definitely caused by the theme?

- [X] I have checked the app behavior without the theme and it is different

### Environment & Computer Info

```Markdown
- Spotify version: 1.2.37.701
- Installed from: AUR
- Spicetify version: v2.36.12
- Color scheme: darkmono
- Extensions: Better lyrics, Adblockify, section marker, play a random song, LuckyLP
- Custom apps: None
- Bloom installation method: Marketplace
- Screen resolution: `1366x768`
```

### Description

1. `Marketplace > Installed`, a weird fade on the extension's title.
2. No vertical margins with the upper bar tabs
3. Offset on the upper right `Profile`, `Friends` and `Notifications` buttons

### 1 
![image](https://github.com/nimsandu/spicetify-bloom/assets/68474172/19bc3372-1099-476f-a47d-6139012bb0e9)
### 2
![image](https://github.com/nimsandu/spicetify-bloom/assets/68474172/5c34dd4a-2a60-4c1b-a717-1fa127e22f10)

**Comment by nimsandu** [comment]
the top bar was patched with the latest commit, can you update and check that please?

**Comment by Esquii-pixel** [comment]
Hi, the theme is so good, but i dont see the play/pause button. I cheked all extensions, custom apps...
![Captura de pantalla 2024-06-03 235616](https://github.com/nimsandu/spicetify-bloom/assets/128618528/dcdc4d6d-ecd7-48b1-bd59-8bf9c0338832)

**Comment by aurelbdx** [comment]
Hi, 
same problem with play/pause button.
Another problem, with "Better local files" (https://github.com/Pithaya/spicetify-apps-dist) 
I can't click on Titre (Title), Albums and Artistes.

<img width="400" alt="ok" src="https://github.com/nimsandu/spicetify-bloom/assets/29289789/999f0a77-5fb7-4f9a-ab18-ab6107b0e6e9">

**Comment by Esquii-pixel** [comment]
> the top bar was patched with the latest commit, can you update and check that please?

check if u have installed "Remove top spacing", is a code

**Comment by kamez104** [comment]
I'm glad the typing bug has finally been fixed, but there are still many issues. The play/pause button is missing, the cards look misaligned (might be intentional idk), and the back/forward buttons are both non-functional and misaligned. There are also some overflowing icons on the right.
![image](https://github.com/nimsandu/spicetify-bloom/assets/138945522/c4aaf237-d1c5-4412-9722-19fa2f21ae49)

**Comment by kamez104** [comment]
> back/forward buttons are both non-functional and misaligned

I can open a separate issue for this if you want

https://github.com/nimsandu/spicetify-bloom/assets/138945522/fc54ec20-8dc7-481e-b92f-04db35eb1134

**Comment by kamez104** [comment]
![image](https://github.com/nimsandu/spicetify-bloom/assets/138945522/0897a3ad-3b0f-4873-8437-d41c0ce87834)
just letting you know the play/resume button is still broken

**Comment by kamez104** [comment]
I also noticed strange border radius behavior when a tooltip is displayed over something in dark-fluent 
![obraz](https://github.com/nimsandu/spicetify-bloom/assets/138945522/42582022-d4cb-437c-b026-868d8440fff4)

**Comment by nimsandu** [comment]
@Yashirow @kamez104 search tab is fixed now, do we still have the issue with search bar?

**Comment by kamez104** [comment]
Nope, still here
![image](https://github.com/nimsandu/spicetify-bloom/assets/138945522/24a225ac-eb74-42df-9213-189e55f2f70a)

**Comment by sanoojes** [comment]
i will add a quick fix for this rn !

**Comment by Yashirow** [comment]
> @Yashirow @kamez104 search tab is fixed now, do we still have the issue with search bar?

@nimsandu Search tab is fixed 👍🏻 but the play button is still broken
