### ISSUE TITLE
Missing "Create-Playlist", "Liked Songs" and "Episodes" icons and some playlist icons are cropped

### ISSUE THREAD

**Issue by Astromations** [nimsandu/spicetify-bloom#36]
I'm on Spotify version 1.1.87.612.gf8d110e2 
![image](https://user-images.githubusercontent.com/80211195/176190850-452faa2c-6688-4852-96a5-3e148fb49ab7.png)
and Spicetify version 2.10.1
![image](https://user-images.githubusercontent.com/80211195/176190956-e772acd7-7442-4cac-ace1-8a823f437972.png)

Mising icons:
![image](https://user-images.githubusercontent.com/80211195/176191389-6e53ec48-ce89-4442-a733-b5d20b663c8a.png)

playlist icons get cropped
![image](https://user-images.githubusercontent.com/80211195/176191487-9481b9d7-7a6c-4bfb-a861-771db05227e4.png)
![image](https://user-images.githubusercontent.com/80211195/176191510-d80f52c9-99e4-4209-b990-9189356b1b07.png)
![image](https://user-images.githubusercontent.com/80211195/176191542-95ad420e-c069-4306-9c0a-748432ebac15.png)

**Comment by Astromations** [comment]
also idk if this is an issue or intended design but the playlist icons in the homepage have visible borders in their corners
![image](https://user-images.githubusercontent.com/80211195/176192389-d30b8d12-552b-433d-aafa-6d34a31f4fcf.png)
![image](https://user-images.githubusercontent.com/80211195/176192428-d0b1d3b4-059e-4234-bf74-ee8f66c93db7.png)

**Comment by nimsandu** [comment]
We will fix that asap

**Comment by nimsandu** [comment]
@Astromations Bug fixed by @kyrie25
