### ISSUE TITLE
UI still not fixed.

### ISSUE THREAD

**Issue by Nimai-HK** [nimsandu/spicetify-bloom#360]
### Did you read the README?

- [X] I have read the README, the theme is installed/configured correctly and the "Troubleshooting" section contains no information related to my problem

### Do you have the latest versions of Spicetify, Spotify and Bloom?

- [X] I'm using the latest versions of Spicetify, Spotify and Bloom

### Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Is your problem definitely caused by the theme?

- [X] I have checked the app behavior without the theme and it is different

### Environment & Computer Info

```Markdown
Spotify for Windows (64 bit)
1.2.39.578.g0ea3f38b
Spicetify v2.36.13
Theme: Bloom / darkmono
Extensions: adblock.js, fullAlbumDate.js, volumePercentageWrapper.js, QueueTime.js, npvAmbience.js, scannables.js, utilities.js, cacheCleaner.js, hidePodcasts.js, theme.js
Custom apps: marketplace
xpui_2024-05-31_1717155884878_0ea3f38
cef_124.3.5+gff7dcd8+chromium-124.0.6367.119
Runtime: Chrome
Build System: CMake
- Bloom installation method: (Spicetify Marketplace/PowerShell script/Manual) (effective to all three)
```

### Description

UI still gets displaced, title bar rendering not fixed, search option glitched out.
title bar aviation, home button, marketplace button does not work. Typing into the search field issue has now been fixed, but still, the text typed is not visible

I think this is applicable on smaller displays.. Hasn't been fixed.

### Screenshots

![image](https://github.com/nimsandu/spicetify-bloom/assets/169251488/05f56fb5-561b-44ae-a604-3fc3214cc13f)
![image](https://github.com/nimsandu/spicetify-bloom/assets/169251488/a0970c29-2487-431d-8e18-4540200fe40b)

**Comment by nimsandu** [comment]
@Nimai-HK looks like your spotify app is using one of the experimental features! 
ill help you resolve the issue, 

1. > i can barely see your profile icon, click on a visible place, and click experimental features on the context menu to bring up the experimental dialog box.
2. > in this dialog box, tap on the search box and search for Home
3. > find the highlighted setting from the list and then select CONTROL option from the dropdown list.
4. > ![image](https://github.com/nimsandu/spicetify-bloom/assets/57834844/915c09ce-b43f-41ca-af89-b75b3319cdd9)


also afterwards, try updating spicetify with the command `spicetify upgrade` and re run the bloom installer to make sure everything is up to date!

```powershell
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
iex "& { $(iwr -useb 'https://raw.githubusercontent.com/nimsandu/spicetify-bloom/main/install/PowerShell/Bloom.ps1') }"
```

**Comment by Nimai-HK** [comment]
That worked. But there's a lot of UI misplacement after that.
some buttons are still unclickable..

**Comment by Nimai-HK** [comment]
![image](https://github.com/nimsandu/spicetify-bloom/assets/169251488/e0fa338d-06ea-4d1f-a948-28934110c78b)
it's the most recent version of bloom

**Comment by nimsandu** [comment]
oh nice! @Nimai-HK can you please mention all the things that doesnt work as expected? if you can, please take a moment to mention all of em so we can fix it asap with the next fixes

**Comment by Nimai-HK** [comment]
stuff's (play buttons) misaligned, 
in the friend activity tab, text is not visible in some themes.

The bloom effect on the now playing bar is lighter now?
( I suppose the saturation was decreased and overlay opacity was increased to some extent to make it to make more light weight compared to previous versions)

that's all..

oh and also a recommendation- 
1)playlist headers getting a blurred effect of the album art (similar to that in comfy themes)
2) NPV ambience for album art inbuilt for now playing view

**Comment by Nimai-HK** [comment]
![image](https://github.com/user-attachments/assets/693166d9-b111-4473-ba75-04c77ef3e84c)
the displacement just got worse- spotify got an update and on applying spicetify backup it turned out like this.

Spotify for Windows (64 bit)
1.2.44.405.g81fd6352
Spicetify v2.37.1
Theme: Bloom / dark-fluent
Extensions: adblock.js, fullAlbumDate.js, volumePercentageWrapper.js, QueueTime.js, scannables.js, utilities.js, cacheCleaner.js, hidePodcasts.js, oldLikeButton.js, playlist-icons.js, npvAmbience.js
Custom apps: lyrixed, marketplace
xpui_2024-08-09_1723192885229_81fd635
cef_125.0.19+g3d8f1c9+chromium-125.0.6422.112
Runtime: Chrome
Build System: Bazel

**Comment by MrBiscuit921** [comment]
![image](https://github.com/user-attachments/assets/788ae98d-83c8-45ef-9f4b-76faa8391606)
window controlls overlap
![image](https://github.com/user-attachments/assets/1e5f1fdf-afe5-40ca-8f4f-ed0dd0d6280a)
no gap between playlist on home page

**Comment by sanoojes** [comment]
I apologize for the delay in fixing this. I was occupied with work on a different theme.
