### ISSUE TITLE
Back button is misaligned 

### ISSUE THREAD

**Issue by LarveyOfficial** [nimsandu/spicetify-bloom#37]
The previous track button is higher than it should be 

![image](https://user-images.githubusercontent.com/39219859/176594278-db0bb354-1b30-4fb9-b920-4cb1b71544b2.png)

![image](https://user-images.githubusercontent.com/39219859/176594302-a210dccb-95f6-40ee-840d-f69647c4d17a.png)

**Comment by LarveyOfficial** [comment]
P.S
Spotify Version 1.1.88.612.gcc529952
Spicetify 2.10.2
and 1920x1080 screen (16:9)

**Comment by LarveyOfficial** [comment]
#39 seems to address this

**Comment by nimsandu** [comment]
Pull request merged

**Comment by nimsandu** [comment]
Now you might good to go
