### ISSUE TITLE
Liked Songs Icon Still Missing

### ISSUE THREAD

**Issue by LarveyOfficial** [nimsandu/spicetify-bloom#42]
Spotify Version : Spotify for Windows 1.1.88.612.gcc529952

Spicetify Version : 2.10.2

Bloom Version : Newest

After a fresh install it seems the newest pull fixed my last issue with the icons being cut in half, although it seems the liked songs icon is still missing.

![image](https://user-images.githubusercontent.com/39219859/177193896-5d10f846-6a93-4ae6-ab83-384f6d14008d.png)

I've also tried using the snippet called "Fix 'Liked' Icon" but it also does not solve the issue.

**Comment by kyrie25** [comment]
Mb, I forgot to push the new CSS map changes in accordance to the patch I made last night.
It has been done anw (spicetify/spicetify-cli#1809) so try `spicetify restore backup apply` and see the new changes.

**Comment by LarveyOfficial** [comment]
Works!
