### ISSUE TITLE
Playlists with non 1:1 icon images get cropped in the sidebar 

### ISSUE THREAD

**Issue by Astromations** [nimsandu/spicetify-bloom#44]
![image](https://user-images.githubusercontent.com/80211195/177377343-bc0bef23-fc15-49a4-8431-532e401116f5.png)

Based on a 16:9 image 
![image](https://user-images.githubusercontent.com/80211195/177377682-623ec7a2-841d-4030-b669-a9f4b5659e33.png)

**Comment by Astromations** [comment]
Separate issue:
![image](https://user-images.githubusercontent.com/80211195/177388896-c4ee8eec-90ce-4193-9dc7-e13949a9df8d.png)
at a certain number of playlists in the sidebar, the playlist lowest down gets cut off. Especially noticeable when you expand folders. This happened to me at about 16 playlists visible ( counting the folders)

**Comment by nimsandu** [comment]
We are currently working on this issue

**Comment by kyrie25** [comment]
Do you wish for the background image to be centered or for the entire image to be visible? The latter looks kinda undesirable tbh.
![Uploading image.png…]()
