### ISSUE TITLE
Enlarged album art issue

### ISSUE THREAD

**Issue by nediaH** [nimsandu/spicetify-bloom#46]
![image](https://user-images.githubusercontent.com/41041630/177622450-965042d7-0e6c-4a53-b681-b9d3d6595d18.png)

When I enlarge the album art, the small album art doesn't disappear, it just moves to the left then stays half clipped off the app.

**Comment by nimsandu** [comment]
@nediaH I also noticed that one

**Comment by nimsandu** [comment]
Im trying to fix that

**Comment by nimsandu** [comment]
@nediaH Issue fixed by @Astromations
