### ISSUE TITLE
Downloading status broken

### ISSUE THREAD

**Issue by LarveyOfficial** [nimsandu/spicetify-bloom#49]
Spotify Version: Spotify for Windows 1.1.88.612.gcc529952
Spicetify Version: 2.10.2

When downloading something, both the liked songs icon and the library button break

![image](https://user-images.githubusercontent.com/39219859/177889461-ea9db5fc-7e16-4612-bb15-5a68eb83c9d2.png)

The Liked Songs button stays like this even after downloads are finished:
![image](https://user-images.githubusercontent.com/39219859/177889500-18ebb7d1-25c6-41ea-b212-8a683e946db5.png)

**Comment by nimsandu** [comment]
We can try enhancing it 
But i don't have premium 🥲

**Comment by nimsandu** [comment]
@LarveyOfficial Lets see what we can do

**Comment by nimsandu** [comment]
@Astromations fixed the issue by hiding those elements

**Comment by nimsandu** [comment]
But in near future we will try to bring them back as well suited progress bar which match with fluent systems and bring additional functionality

**Comment by nimsandu** [comment]
For now im closing this issue
But don't hesitate to open another issue when ever you want @LarveyOfficial
