### ISSUE TITLE
Suggestion: Make the left sidebar bigger and show the playlist names instead of just the icon

### ISSUE THREAD

**Issue by My-Name-Is-Adam** [nimsandu/spicetify-bloom#50]
When you have a lot of playlists it's not easy to identify the playlist by just the icon. It would be good if the sidebar was bigger to enable so we can see the full playlist names. 

Great theme by the way. 

Thank you.

**Comment by My-Name-Is-Adam** [comment]
Would also be good if it changed to light/dark mode as per the system. With another theme it changes automatically to the light/dark version but I have to do it manually with this theme.

**Comment by nimsandu** [comment]
In this case we have to follow windows 11 fluent systems 

So we can't make it wider 

But if we can expand it on hover or add a hover panel 

It might good to protect fluent  theme scheme
