### ISSUE TITLE
How to hide fullscreen button?

### ISSUE THREAD

**Issue by LarveyOfficial** [nimsandu/spicetify-bloom#54]
I noticed on the screenshots in the readme there is no fullscreen button.

How can I replicate this as I have a fullscreen button.
Is it a config setting?

**Comment by nimsandu** [comment]
@LarveyOfficial i have full screen button too on my Spotify 
But I installed it using spicetify marketplace 
I haven't included that on screenshot because its not a part of pure theme

You can install full screen option via marketplace and even delete it via marketplace 

Its not a part of theme

**Comment by nimsandu** [comment]
@LarveyOfficial Did my explanation clear?
Let me know
Then close the issue 
If my answer is awkward don't hesitate to reach me out

**Comment by nimsandu** [comment]
![image](https://user-images.githubusercontent.com/57834844/178098131-6ef1a7b2-abe6-411e-8fb8-d6fa27549133.png)

**Comment by LarveyOfficial** [comment]
Ah I understand, I actually want to use a custom fullscreen button I found on the marketplace, how can I remove the default spotify one?

**Comment by nimsandu** [comment]
@LarveyOfficial Ill tell you if i figure out a way

**Comment by nimsandu** [comment]
@LarveyOfficial Did you find a way to hide the button

**Comment by LarveyOfficial** [comment]
I have not

**Comment by nimsandu** [comment]
Not nice

**Comment by LarveyOfficial** [comment]
I was able to figure out how to hide it,
You need to first install the CSS Injector Extension from the Spicetify Marketplace
Then you need to make a new Snipper which includes the follow CSS code
```css
button[title="Full screen"]{ display:none; }
```

**Comment by nimsandu** [comment]
If you are done plz close the issue
