### ISSUE TITLE
Suggestion: Automatic day/night theme change support.

### ISSUE THREAD

**Issue by SupLiCatinG** [nimsandu/spicetify-bloom#55]
We can already patch spotify to follow system scheme, while using custom .js why we can't add automatic day/night color scheme switch ?

**Comment by nimsandu** [comment]
Yeah that will be a great functionality

**Comment by nimsandu** [comment]
But bloom theme is dark oriented theme, to successfully implement this feature we must enhance light theme first

**Comment by SupLiCatinG** [comment]
> But bloom theme is dark oriented theme, to successfully implement this feature we must enhance light theme first
> 
> And that's going to take some time

Sorry about referencess, Spicetify Default Dynamic theme has this feature, you can take inspire from them. It uses custom .js to switch colors. For Light theme, Fluent theme already has Light orianted color scheme you can use it.

**Comment by nimsandu** [comment]
Bloom and fluent themes are associated
So we have a light theme too
But we got some bugs on light theme
Im currently working on to fix them 
Afterwards ill try to implement this option 
@SupLiCatinG
