### ISSUE TITLE
Typo in readme??

### ISSUE THREAD

**Issue by javalsai** [nimsandu/spicetify-bloom#60]
Is this a typo of `</div>`??
https://github.com/nimsandu/spicetify-bloom/blob/74882993ee51eeeaf34157f7600fe0c049d1f0ff/README.md?plain=1#L8

It's causing the whole readme to be inside the [`div`](https://github.com/nimsandu/spicetify-bloom/blob/74882993ee51eeeaf34157f7600fe0c049d1f0ff/README.md?plain=1#L6) and to be centered because of that.

**Comment by kyrie25** [comment]
Next time just make a PR lol.

**Comment by nimsandu** [comment]
oops ig
