### ISSUE TITLE
How to uninstall Bloom>

### ISSUE THREAD

**Issue by Ezzzzyz** [nimsandu/spicetify-bloom#75]
I'd like to uninstall bloom but everytime i redownload spicetify the default theme is bloom. It messes up the other themes that I would like to use from the marketplace.
Also instead of downloading from the marketplace I used the command feature from here on powershell.

**Comment by nimsandu** [comment]
GO TO `C:\Users\<username>\.spicetify\Themes` and delete _bloom_ folder
then open "C:\Users\<username>\.spicetify\config-xpui.ini" via notepad and remove following parts 
![image](https://user-images.githubusercontent.com/57834844/181684279-d3411464-a85b-40a3-b989-27c151ffc1ae.png)
then run `spicetfy apply` 
after that uninstall spicetify and install spicetfy again
you might good to go

just a one thing "do you hate bloom? or not interested on bloom?"
we can shape our future by listening to your feedback

**Comment by nimsandu** [comment]
@Ezzzzyz ???

**Comment by MGPlayzYT** [comment]
might include an uninstallation guide in the readme soon

**Comment by nimsandu** [comment]
@MGPlayzYT hmm yap but i never thought someone would uninstall this stunning theme
