### ISSUE TITLE
Song Name loses blurred background around it 

### ISSUE THREAD

**Issue by 14142000** [nimsandu/spicetify-bloom#8]
Around the song name there's a distortion of the blur effect that is  extremely distracting
![image](https://user-images.githubusercontent.com/3375830/168403991-c31a2ef1-26e1-4a45-86ef-09c6929b0cf2.png)

**Comment by nimsandu** [comment]
yah that one is completely distracting 
but sorry i have a problem over here
![image](https://user-images.githubusercontent.com/57834844/168469701-9c7c90fd-879a-424f-8f66-ea56f5148a3e.png)

my spotify is not even loading and i am hoping for a helping hand

**Comment by nimsandu** [comment]
hello reinstall the theme again now and you will be good to go
with out distracting

**Comment by 14142000** [comment]
This update broke the alignment of the sidebar
![image](https://user-images.githubusercontent.com/3375830/168909965-3c12498c-3b64-4358-bbc9-0e3b2b84d2a4.png)

**Comment by nimsandu** [comment]
hmm
problem after problem right?
lets see what we can do

**Comment by 14142000** [comment]
I have learned like life itself anything you program will always be a work in progress as well lol

**Comment by nimsandu** [comment]
❤️

**Comment by nimsandu** [comment]
Your problems are now solved
Im closing this issue 
But create new one whenever you find a new one @14142000
