### ISSUE TITLE
bugs with play bar and sound bar

### ISSUE THREAD

**Issue by davimaiaa** [nimsandu/spicetify-bloom#81]
![image](https://user-images.githubusercontent.com/67204261/183274900-0cf78ed3-67a1-4502-bba1-471e48867f28.png)
When listening to songs, the progress bar is compromised, just as the sound bar. You can see that on my printscreen

**Comment by nimsandu** [comment]
You have moved from fluent theme aren't you

**Comment by nimsandu** [comment]
Send a screenshot of your xpui file ill tell you what to do

**Comment by nimsandu** [comment]
@davimaiaa

**Comment by davimaiaa** [comment]
Yes! I moved from Fluent! As you asked, here's the xpui file screenshot! Btw thanks for the help
![image](https://user-images.githubusercontent.com/67204261/183301082-7ceabb38-6585-4635-aaad-7d23672ade29.png)

**Comment by davimaiaa** [comment]
@nimsandu

**Comment by davimaiaa** [comment]
I completely reinstalled spicetify and now it's working! tks for the great theme bro

**Comment by nimsandu** [comment]
@davimaiaa All right enjoy calm design 

If you having any confusions don't hesitate to open another issue
