### ISSUE TITLE
Mica/Blur effect looking weird

### ISSUE THREAD

**Issue by SapitoSucio** [nimsandu/spicetify-bloom#9]
Hello there, first of all this theme is amazing, I love it.

After using it a bit, I couldn't help but notice that the mica/blurry effect looks a little bit weird

Moving slowly through some elements you can see how it behaves and it just looks weird to me, maybe too much flickering? 

https://user-images.githubusercontent.com/7357354/168728633-69cd8cfb-6699-4bc9-a6b9-4e2c332a0513.mp4

.

**Comment by nimsandu** [comment]
i recognized that too
lets try fixing that in the near future

**Comment by nimsandu** [comment]
Fixed in the latest version

**Comment by nimsandu** [comment]
> Hello there, first of all this theme is amazing, I love it.
> 
> 
> 
> After using it a bit, I couldn't help but notice that the mica/blurry effect looks a little bit weird
> 
> 
> 
> Moving slowly through some elements you can see how it behaves and it just looks weird to me, maybe too much flickering? 
> 
> 
> 
> https://user-images.githubusercontent.com/7357354/168728633-69cd8cfb-6699-4bc9-a6b9-4e2c332a0513.mp4
> 
> 
> 
> .

Thanx for your amazing trust and patience
