### ISSUE TITLE
Play/pause button glitch in main menu and playlist.

### ISSUE THREAD

**Issue by vathanac** [nimsandu/spicetify-bloom#92]
Spotify for Windows
1.1.91.824.g07f1e963

[Main menu](https://i.imgur.com/qBmv3Rh.png)

[Playlist](https://i.imgur.com/GtNOwgy.png)

**Comment by MGPlayzYT** [comment]
This seems to be more of an issue on your side. Try resetting Spotify back to it's original look. (re-installing is recommended), apply the theme, and see if the issue still persists.

**Comment by nimsandu** [comment]
It doesn't seems to be @MGPlayzYT issue from his side 
Even i started experience this issue today morning after updating Spotify

**Comment by MGPlayzYT** [comment]
> It doesn't seems to be @MGPlayzYT issue from his side Even i started experience this issue today morning after updating Spotify

@nimsandu it seems to be because I'm using an older version of Spotify (which is `1.1.91.824`). the latest version is `1.1.92.647`, and that might be the culprit. In the meantime, downgrade your version to `1.1.91.824` till the issue is fixed. (I'll see if I can fix it tomorrow)

**Comment by nimsandu** [comment]
@MGPlayzYT Thanks friend 🤞

**Comment by MGPlayzYT** [comment]
Update: seems like I don't know how to fix this issue. I'll leave it up to someone who knows how to fix this. In the meantime, the temporary solution is to downgrade your Spotify version to `1.1.91.824`.

**Comment by nimsandu** [comment]
@MGPlayzYT Yah even i can't find a perfect way to fix it 
So we have to wait for a genius
What about @kyrie25 🙃

**Comment by kyrie25** [comment]
> @MGPlayzYT Yah even i can't find a perfect way to fix it So we have to wait for a genius What about @kyrie25 🙃

Will be resolved via spicetify/spicetify-cli#1875

**Comment by nimsandu** [comment]
@kyrie25  thanks mr.Genius

**Comment by nimsandu** [comment]
are we good to close this issue @vathanac ?
the solution for all of us is upgrading spicetify-cli once the latest patch releases 
@kyrie25 's pr has been merged to the cli repo, so latest version will be available soon

special thanks to @MGPlayzYT and @kyrie25 

@vathanac let me know whether we can close this issue

**Comment by vathanac** [comment]
> are we good to close this issue @vathanac ? the solution for all of us is upgrading spicetify-cli once the latest patch releases @kyrie25 's pr has been merged to the cli repo, so latest version will be available soon

thanks for the update!

**Comment by nimsandu** [comment]
@vathanac if you having any other issue don't hesitate to open another issue 
enjoy bloom
