### ISSUE TITLE
Non visual play/pause button and duplicate slider-dot and some fix is needed

### ISSUE THREAD

**Issue by afi-dev** [nimsandu/spicetify-bloom#95]
Conditions to reproduce : 
Spicetify version : 2.11.1
Spotify version : Spotify for Windows 1.1.92.647.ga4397eb7
Spicetify Marketplace installed : Yes

Some features do not work on the css side for the latest version of Spotify version 1.1.92.647.ga4397eb7 and Spicetify version 2.11.1

CSS Hotfix needed :
- Play/Pause svg button did not work (not show but functionnal)
- Slider-dot is duplicate
- User profil have an unexpected paddind 
- Made For You is not correctly Designed
- Button Playlist, Artist and Album is not center
- Some buttons have the old focus color (Playlists, Artists, Album, Sidebar config, Account, Profile, Private session, Settings, Log out)
- Sidebar config pop-over in sidebar need redesign
- Fullscreen need redesign 

![image](https://user-images.githubusercontent.com/44731817/185803547-364a1ddc-67f3-4e54-981b-244649d09be4.png)
![image](https://user-images.githubusercontent.com/44731817/185803960-f599223e-ea5e-4f78-bea0-2701d0d38be7.png)

I tried to fix some visual problems myself on the css side as well as in the bloom.js but I didn't manage to fix the play/pause button problem.

More cordially, hoping you can update the theme. Afi

**Comment by MGPlayzYT** [comment]
This is an issue with `spicetify` not working well with the latest Spotify update, which is `1.1.92.647`.

**Comment by afi-dev** [comment]
Yes but it seems to me right because Specitify have made important changes... So maybe yes but Spotify have recently added new graphical elements to Spotify which could explain why Specitify is bad on certain things, so in the end I don't see what the problem is, it's not up to Specitify to fix the visual problem but you

**Comment by nimsandu** [comment]
We will pay our attention about this @afi-dev this might happening because spicetify css map doesn't match with new Spotify update or else this might our fault 

We will work regarding this

**Comment by kyrie25** [comment]
> Yes but it seems to me right because Specitify have made important changes... So maybe yes but Spotify have recently added new graphical elements to Spotify which could explain why Specitify is bad on certain things, so in the end I don't see what the problem is, it's not up to Specitify to fix the visual problem but the theme author

The theme is dependent on Spicetify's wrapper functions to execute the extension that's bundled with the theme, for which is broken on Spicetify `2.11.1` and Spotify `1.1.92`, all of this has been patched on the `Dev` version of Spicetify and will be resolved as soon as we push a new release.

**Comment by nimsandu** [comment]
@afi-dev That is what @MGPlayzYT also talked about hope you will understand 

@kyrie25 i really appreciate your deep explanation 
Thanks a lot

**Comment by kyrie25** [comment]
Resolved via [`Spicetify CLI v2.12.0`](https://github.com/spicetify/spicetify-cli/releases/tag/v2.12.0)

**Comment by nimsandu** [comment]
@afi-dev After updating spicetify do you still having troubles or issues with bloom?

**Comment by nimsandu** [comment]
@afi-dev Dear user please tell us whether hou still having problems with bloom 
We are waiting for your confirmation 
We might have to close this issue as an inactive issue if we can't get your confirmation regarding this issue

**Comment by OxygenEgg** [comment]
I also have the play/pause buton and the fullscreen issues (persistent after updating spicetify)

**Comment by nimsandu** [comment]
@OxygenEgg Have you updated spicetify 
Could you please mention the spicetify version

**Comment by OxygenEgg** [comment]
it's 2.12.0

**Comment by OxygenEgg** [comment]
also the play/pause button sometimes doesn't show up

**Comment by nimsandu** [comment]
@kyrie25 sorry to bother you dude but do you have any recommendations to fix this issue ?

**Comment by kyrie25** [comment]
I don't have much free time recently so I can't guarantee anything. Will look into it when I can.

**Comment by Georgetheasian** [comment]
Hi, just updated spicetify to 2.13.0 and this issue still seems to be present

**Comment by nimsandu** [comment]
@Georgetheasian if you have installed it using marketplace try installing it using powershell script in the readme.md

**Comment by Georgetheasian** [comment]
I installed it again using powershell but nothing changed. I will try using marketplace and seeing if that changes anything.

**Comment by Georgetheasian** [comment]
Marketplace also changed nothing, Im not sure if manual installation will change anything.

**Comment by nimsandu** [comment]
@Georgetheasian Can you share a screenshot with us

**Comment by nimsandu** [comment]
> Marketplace also changed nothing, Im not sure if manual installation will change anything. 

Complete uninstall and full reinstallation via script might also help us to determine the problem

**Comment by afi-dev** [comment]
What did u mean ?

**Comment by nimsandu** [comment]
> What did u mean ?

which message you talking about ? can you quote it

**Comment by nimsandu** [comment]
> > Marketplace also changed nothing, Im not sure if manual installation will change anything.
> 
> Complete uninstall and full reinstallation via script might also help us to determine the problem

i meant proceeding following steps
>reset spicetify and removing all the bloom theme files and going back to default spotify theme 
>and uninstalling the spicetify-cli and removing every file related to spicetify
>running following ps script to reinstall spicetify and bloom theme 
`Invoke-WebRequest -UseBasicParsing "https://raw.githubusercontent.com/nimsandu/spicetify-bloom/main/install.ps1" | Invoke-Expression`

**note- you don't have to install spicetify-cli separately before or after running above script**

afterwards can you kindly share your experience with us, so we can fix this issue at ease

**Comment by Georgetheasian** [comment]
Hello, I have just followed the instructions and it still seems to be an issue. Usually, the play button was there but did not function properly. Other times however, the play button is not there at all when my mouse hovers over.

**Comment by nimsandu** [comment]
@Georgetheasian Can you share a screenshot

**Comment by nimsandu** [comment]
The play button everywhere except player is not working and im working on to fix it 
If its the problem can you open another issue for that

**Comment by Georgetheasian** [comment]
As for the instructions, I reset the spotify,  went into the Appdata and local and roaming folders to delete spicetify. After that I used powershell and just pasted the command in.

**Comment by Georgetheasian** [comment]
Yes sure, for me its just the playlist and daily mixes.

**Comment by nimsandu** [comment]
> As for the instructions, I reset the spotify,  went into the Appdata and local and roaming folders to delete spicetify. After that I used powershell and just pasted the command in. 

Nice please send a screenshot whenever possible for you

**Comment by Georgetheasian** [comment]
1.  Restore spotify to original state
![image](https://user-images.githubusercontent.com/80559769/188782496-a38e4195-089d-4a73-80d7-eb7493db280e.png)

2. Delete spicetify files in appdata. Local and roaming 
![image](https://user-images.githubusercontent.com/80559769/188782730-24c13c8a-3264-4fe9-808b-62b6beb0f7d7.png)

![image](https://user-images.githubusercontent.com/80559769/188782810-776ce017-de18-449d-b0b3-3523e3d02f45.png)

3. Use powershell to install spicetify and bloom 
![image](https://user-images.githubusercontent.com/80559769/188782914-c5e9e66d-de83-4b83-9f35-f2b0d78a062b.png)

4. Restart and apply to spotify
![image](https://user-images.githubusercontent.com/80559769/188783021-dd9e683a-c433-4d42-975a-e3c685d75f96.png)

**Comment by nimsandu** [comment]
As according to @Georgetheasian screenshot on issue #101 most of ui issues are solved by above steps 
Play button issue is a separate issue 
I recommend you to get trough above steps and let me know what happens

**Comment by nimsandu** [comment]
> 1.  Restore spotify to original state
> 
> ![image](https://user-images.githubusercontent.com/80559769/188782496-a38e4195-089d-4a73-80d7-eb7493db280e.png)
> 
> 
> 
> 2. Delete spicetify files in appdata. Local and roaming 
> 
> ![image](https://user-images.githubusercontent.com/80559769/188782730-24c13c8a-3264-4fe9-808b-62b6beb0f7d7.png)
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/80559769/188782810-776ce017-de18-449d-b0b3-3523e3d02f45.png)
> 
> 
> 
> 3. Use powershell to install spicetify and bloom 
> 
> ![image](https://user-images.githubusercontent.com/80559769/188782914-c5e9e66d-de83-4b83-9f35-f2b0d78a062b.png)
> 
> 
> 
> 4. Restart and apply to spotify
> 
> ![image](https://user-images.githubusercontent.com/80559769/188783021-dd9e683a-c433-4d42-975a-e3c685d75f96.png)
> 
> 
> 
>  

Thanks sir
Ill even include this on readme

**Comment by nimsandu** [comment]
@afi-dev Hope this will fix the issue

**Comment by Georgetheasian** [comment]
No problem, its always a pleasure to help. Its an amazing theme and I want to help improve it.

**Comment by nimsandu** [comment]
@Georgetheasian ❤️
Ill leave this open for a while for others to conform

**Comment by MGPlayzYT** [comment]
> 1. Restore spotify to original state
>    ![image](https://user-images.githubusercontent.com/80559769/188782496-a38e4195-089d-4a73-80d7-eb7493db280e.png)
> 2. Delete spicetify files in appdata. Local and roaming
>    ![image](https://user-images.githubusercontent.com/80559769/188782730-24c13c8a-3264-4fe9-808b-62b6beb0f7d7.png)
> 
> ![image](https://user-images.githubusercontent.com/80559769/188782810-776ce017-de18-449d-b0b3-3523e3d02f45.png)
> 
> 3. Use powershell to install spicetify and bloom
>    ![image](https://user-images.githubusercontent.com/80559769/188782914-c5e9e66d-de83-4b83-9f35-f2b0d78a062b.png)
> 4. Restart and apply to spotify
>    ![image](https://user-images.githubusercontent.com/80559769/188783021-dd9e683a-c433-4d42-975a-e3c685d75f96.png)

Thanks for making a guide! I'll add this to the README soon.

**Comment by nimsandu** [comment]
@MGPlayzYT ❤️

**Comment by nimsandu** [comment]
@Georgetheasian @MGPlayzYT  and all the participants,
im closing this issue 
i added the uninstallation guide to the readme and also i didn't forgot to credit you @Georgetheasian 
thanks for everything
together we can make this stunning theme even better
