### ISSUE TITLE
Lyrics move Spotify up

### ISSUE THREAD

**Issue by HypedDomi** [nimsandu/spicetify-bloom#99]
When you open the Lyrics Page (native Spotify Lyrics) and the Song comes to an end, it moves the whole page up
![image](https://user-images.githubusercontent.com/50876016/187555758-501bc950-a19a-4524-a483-c9328ecc2666.png)

**Comment by nimsandu** [comment]
@MGPlayzYT any suggestion regarding this Sir ?

**Comment by nimsandu** [comment]
@HypedDomi Im out for a while so it will take some time to fix the issue 

Please be patient 

Thanks for letting us know this problem your suggestion make bloom better

**Comment by MGPlayzYT** [comment]
> @MGPlayzYT any suggestion regarding this Sir ?

I'm not really sure what's causing this but it probably has something to do with Spicetify.

**Comment by HypedDomi** [comment]
> @HypedDomi Im out for a while so it will take some time to fix the issue
> 
> Please be patient
> 
> Thanks for letting us know this problem your suggestion make bloom better

Yeah thats fine. Take your time 👍

**Comment by MGPlayzYT** [comment]
I'm gonna have to leave this up to someone who knows how to fix this, sorry for the inconvenience.

**Comment by nimsandu** [comment]
@HypedDomi is this issue still presents?

**Comment by HypedDomi** [comment]
The last time i checked it was still there

**Comment by nimsandu** [comment]
try updating Spotify to the latest version and running the installation script again
it must fix the issue

**Comment by nimsandu** [comment]
@HypedDomi

**Comment by lemonbigbig** [comment]
![image](https://user-images.githubusercontent.com/42226640/197926701-419ad5da-c75a-49bb-b089-a5a4a513f067.png)
The fix is not that good

**Comment by HypedDomi** [comment]
> try updating Spotify to the latest version and running the installation script again it must fix the issue

Sadly, I still have the issue. But yeah, I can live with that. It goes back when a new Song starts and only happens in the last 10 Seconds

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/50876016/197959906-67ad99d4-9af6-4fad-b580-4717affbba29.png">

**Comment by nimsandu** [comment]
Sorry for the situation ill try something to fix that I really apologize you both for this problem 

Until I figure out a way to correct this issue I recommend you both to use spicetify lyric plugin for a better experience (this is not a fix, this is just a recommendation as a temporary solution)

**Comment by nimsandu** [comment]
@HypedDomi This issue was fixed by @miukyo so now you might good to go. Btw ill leaves this open for you to conform the fix
Thanks @miukyo  
And all the participants

**Comment by miukyo** [comment]
@nimsandu you're welcome.

**Comment by HypedDomi** [comment]
Yep works. Thank you Miukyo
